### ISSUE TITLE
ERROR 1064 (42000): near 'identified by 'mypass'' at line 1

### ISSUE THREAD

**Issue by sl5net** [dbmail/dbmail#102]
```
$ mysqld --version
/usr/sbin/mysqld  Ver 8.0.22-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
mysql -u root -p
mysql> GRANT ALL ON dbmail.* to dbmail@localhost identified by '<mypass>'
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'identified by 'mypass'' at line 1
```

please compare to line 59 in INSTALL:
`GRANT ALL ON dbmail.* to dbmail@localhost identified by '<pass>'`

Any ideas? Update the INSTALL file?

**Comment by CozC** [comment]
I believe you are using MySQL 8.x  (or compatible with 8.x).
It seems that  you cannot longer use `GRANT ... IDENTIFIED` constructions,  
the recommended way being:


	CREATE USER 'dbmail'@'localhost' IDENTIFIED BY '<pass>';
	GRANT ALL ON dbmail.* TO 'dbmail'@'localhost';


See also [mysql reference 8.0]  
(https://dev.mysql.com/doc/refman/8.0/en/grant.html)
The installation files will be changed accordingly, thanks for point it  
out.

Hope it helps.

-- 
Cosmin Cioranu
