### ISSUE TITLE
create_tables.mysql ERROR 1067 (42000) at line 278: Invalid default value for 'since'

### ISSUE THREAD

**Issue by sl5net** [dbmail/dbmail#103]
I using MySQL 8.x  
```
/dbmail-3.2.3$ mysql -u dbmail dbmail -p < sql/mysql/create_tables.mysql
Enter password: 
ERROR 1067 (42000) at line 278: Invalid default value for 'since'
```

280: ``since` datetime NOT NULL default '0000-00-00 00:00:00',`

https://stackoverflow.com/questions/25349126/how-can-i-set-the-default-value-of-a-field-as-0000-00-00-000000/25351733

this works for me:
'1000-01-01 00:00:00' 
 https://stackoverflow.com/a/46109298/2891692

**Comment by CozC** [comment]
Salve,

Unfortunately, it was not tested in MySQL 8.x versions. Actually the  
newest version does invalidate some assumptions (and constructs) that were  
valid in 5.x series. An update regarding those might be necessary.

It will be on our table to do that. As for the bug mentioned, I do not  
have a fix. You may have to edit that file and do the necessary changes  
(if you do maybe you can request a pull request)



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Fixed
