### ISSUE TITLE
install via make

### ISSUE THREAD

**Issue by sl5net** [dbmail/dbmail#104]
i have successful installed (MySql also installed and configured)

`apt-get -y install make`
# ==> make is already the newest version (4.2.1-1.2).

Whats next?

I reading lots of stuff:

- Development files (libs, scripts and include files) for your database server.
  These will probably be provided by separate packages.
- Glib (>= 2.16) development headers and libraries.
- Gmime (>= 2.4) development headers and libraries.
- libSieve (>= 2.2.1) for Sieve support (libsieve.sf.net).
- Any standard libldap for LDAP support (only tested with OpenLDAP, however).
- mhash
- openssl
- libzdb (http://www.tildeslash.com/libzdb/)
- libevent

Hmmm. Maybe you could add an installer SH-Script?
I've got used to installing everything possible via a sh-script. Do you have that too? For Ubuntu?

**Comment by CozC** [comment]
Salve,

I will be taken into consideration.

Thanks,

-- 
Cosmin Cioranu

**Comment by cncioranu** [comment]
The issue is the fact that are too many distributions, but we will make it for debian and centos.

**Comment by CozC** [comment]
fixed.
