### ISSUE TITLE
LMTP die if sieve redirect has multiple email address

### ISSUE THREAD

**Issue by bajizs** [dbmail/dbmail#106]
Hello,

LMTP service die every time if someone add redirect "address1@domain.tld; address2@domain.tld;"; to sieve script. dbmail-timseieved accept this bad script, and insert it to database.

**Comment by cncioranu** [comment]
Salve, 

I have checked the issue. Indeed there was an issue related to crashing on sieve error and it was fixed. Also an error type of log message will be thrown in the logs if there is a issue with the executed sieve.
On the matter of redirect, the redirects should be specified separately as bellow: 
redirect "address1@domain.tld";
redirect "address2@domain.tld";

On the issue of checking the script, that is on libsieve part, maybe in a future release

**Comment by CozC** [comment]
closing.
