### ISSUE TITLE
Invalid utf8 character string - mysql storage

### ISSUE THREAD

**Issue by bajizs** [dbmail/dbmail#108]
Found errors in error log like:
Error:[message] _header_value_get_id(+1568): SQLException: Invalid utf8 character string: 'F09F8E'

Use mariadb 10.4.14

I see that all table use utf8 encoding, maybe this need to changed to utf8mb4???

**Comment by CozC** [comment]
Indeed, it seems that the code might be related to an emoji. 
Due to the fact that mysql utf8 has a maximum of 3 bytes long, it cannot store the extended utf8 codes, so your suggestin is correct, it will be update accordinly. 

Thank you.

**Comment by bajizs** [comment]
An issue in file dbmail/sql/mysql/upgrades/upgrade.mysql:

If You use database name other then default "dbmail" this conversion can't be successfully finished. Suggest to use data from configuration file.

**Comment by CozC** [comment]
An update will be made to fix this issue.

On Sat, 30 Apr 2022 23:35:22 +0300, Baji Zsolt ***@***.***>  
wrote:

>
> An issue in file dbmail/sql/mysql/upgrades/upgrade.mysql:
>
> If You use database name other then default "dbmail" this conversion  
> can't be successfully finished. Suggest to use data from configuration  
> file.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.



-- 
Cosmin Cioranu
