### ISSUE TITLE
libgmime 2.6

### ISSUE THREAD

**Issue by StefanoBalocco** [dbmail/dbmail#114]
Hello

Ubuntu removed libgmime-2.6 in groovy gorilla.

Do you have any plan to update it to use libgmime-3.0?

**Comment by alan-hicks** [comment]
There is an ongoing pull request for gmime 3
https://github.com/dbmail/dbmail/pull/3

**Comment by StefanoBalocco** [comment]
That pull request seems quite abandoned: last action was more that 1 years ago

**Comment by alan-hicks** [comment]
Upgrading to 3.0 is non trivial and gmime is currently at 3.2 https://developer.gnome.org/gmime/3.2/

2.6 appears to be supported https://launchpad.net/ubuntu/+source/gmime

Patches welcome

**Comment by StefanoBalocco** [comment]
I understand the problem.

2.6 was supported only until focal (included) aka (20)20.04: https://packages.ubuntu.com/focal/libgmime-2.6-dev (not available in newer releases).

**Comment by CozC** [comment]
Done.
