### ISSUE TITLE
Fails to build on Alpine Linux

### ISSUE THREAD

**Issue by fazalmajid** [dbmail/dbmail#123]
dbmail fails to compile on Alpine Linux because it is based on musl libc rather than glibc and  does not have `<sys/queue.h>`:

```
gmake[3]: Entering directory '/home/majid/build/dbmail-3.2.3/src/modules'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc --std=c99 -DHAVE_CONFIG_H -I. -I../..  -I../../src   -I/usr/local/include -I/usr/local/ssl/include -pthread -I/usr/local/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include  -pthread -I/usr/local/include/gmime-2.6 -I/usr/local/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include  -I/usr/local/include/zdb -I/usr/local/include/jemalloc -I/usr/include/jemalloc -W -Wall -Wpointer-arith -Wstrict-prototypes -MT sortnull.lo -MD -MP -MF .deps/sortnull.Tpo -c -o sortnull.lo sortnull.c
libtool: compile:  gcc --std=c99 -DHAVE_CONFIG_H -I. -I../.. -I../../src -I/usr/local/include -I/usr/local/ssl/include -pthread -I/usr/local/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -pthread -I/usr/local/include/gmime-2.6 -I/usr/local/include -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -I/usr/local/include/zdb -I/usr/local/include/jemalloc -I/usr/include/jemalloc -W -Wall -Wpointer-arith -Wstrict-prototypes -MT sortnull.lo -MD -MP -MF .deps/sortnull.Tpo -c sortnull.c  -fPIC -DPIC -o .libs/sortnull.o
In file included from sortnull.c:28:
../../src/dbmail.h:86:10: fatal error: sys/queue.h: No such file or directory
   86 | #include <sys/queue.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
```

Other projects like libevent have approached this problem by bundling a queue.h:

https://github.com/libevent/libevent/issues/343

**Comment by CozC** [comment]
Salve,

Thanks for the input, we will take a look.

Thank you.


On Thu, 03 Jun 2021 19:14:16 +0300, Fazal Majid ***@***.***>  
wrote:

>
> dbmail fails to compile on Alpine Linux because it is based on musl libc  
> rather than glibc and does not have <sys/queue.h>:
> gmake[3]: Entering directory '/home/majid/build/dbmail-3.2.3/src/modules'
> /bin/sh ../../libtool  --tag=CC   --mode=compile gcc --std=c99  
> -DHAVE_CONFIG_H -I. -I../..  -I../../src   -I/usr/local/include  
> -I/usr/local/ssl/include -pthread -I/usr/local/include  
> -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include  
> -I/usr/local/include  -pthread -I/usr/local/include/gmime-2.6  
> -I/usr/local/include -I/usr/local/include/glib-2.0  
> -I/usr/local/lib/glib-2.0/include -I/usr/local/include   
> -I/usr/local/include/zdb -I/usr/local/include/jemalloc  
> -I/usr/include/jemalloc -W -Wall -Wpointer-arith -Wstrict-prototypes -MT  
> sortnull.lo -MD -MP -MF .deps/sortnull.Tpo -c -o sortnull.lo sortnull.c
> libtool: compile:  gcc --std=c99 -DHAVE_CONFIG_H -I. -I../.. -I../../src  
> -I/usr/local/include -I/usr/local/ssl/include -pthread  
> -I/usr/local/include -I/usr/local/include/glib-2.0  
> -I/usr/local/lib/glib-2.0/include -I/usr/local/include -pthread  
> -I/usr/local/include/gmime-2.6 -I/usr/local/include  
> -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include  
> -I/usr/local/include -I/usr/local/include/zdb  
> -I/usr/local/include/jemalloc -I/usr/include/jemalloc -W -Wall  
> -Wpointer-arith -Wstrict-prototypes -MT sortnull.lo -MD -MP -MF  
> .deps/sortnull.Tpo -c sortnull.c  -fPIC -DPIC -o .libs/sortnull.o
> In file included from sortnull.c:28:
> ../../src/dbmail.h:86:10: fatal error: sys/queue.h: No such file or  
> directory
>   86 | #include <sys/queue.h>
>      |          ^~~~~~~~~~~~~
> compilation terminated.
>
> Other projects like libevent have approached this problem by bundling a  
> queue.h:
>
> libevent/libevent#343
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by fazalmajid** [comment]
I worked around sys/queue.h by simply copying another one into dbmail-3.2.2/sys/queue.h

I also had to make these changes to get it to compile:

* add `#include <zdb.h>` before `#include <URL.h` in configure (or acinclude.m4) as at leasy in libzdb 3.2.2 URL.h does not include zdb.h, the latter is necessary to define `bool` by including `<stdbool.h>`
* add `--std=gnu99` to CFLAGS so types like siginfo_t or caddr_t are defined

Also getting this linker error:

```
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: .libs/libdbmail_la-dm_tls.o:(.bss+0x0): multiple definition of `tls_context'; .libs/libdbmail_la-server.o:(.bss+0x68): first defined here
```

This is because `-fno-common` is now the default since GCC 10.x, and the variable is implicitly declared static in both dm_tls.c and server.c. The fix is:

```
--- dbmail-3.2.3/src/dm_tls.c.dist
+++ dbmail-3.2.3/src/dm_tls.c
@@ -31,7 +31,7 @@
 #define THIS_MODULE "tls"
 
 
-SSL_CTX *tls_context;
+extern SSL_CTX *tls_context;
 
 /* Create the initial SSL context structure */
 SSL_CTX *tls_init(void) {
```

Finally, the wiki page for installation omits to mention libzdb is a required dependency.

**Comment by CozC** [comment]
Thanks,

Most helpful.

Nice workaround, now we should evaluate the impact that has over the other  
environments.

Thanks again for the help.

One question: why did you use 3.2.2 for your deployment and not the latest?

On Thu, 03 Jun 2021 21:39:49 +0300, Fazal Majid ***@***.***>  
wrote:

>
> I worked around sys/queue.h by simply copying another one into  
> dbmail-3.2.2/sys/queue.h
>
> I also had to make these changes to get it to compile:
> add #include <zdb.h> before #include <URL.h in configure (or  
> acinclude.m4) as at leasy in libzdb 3.2.2 URL.h does not >include zdb.h,  
> the latter is necessary to define bool by including <stdbool.h>
> add --std=gnu99 to CFLAGS so types like siginfo_t or caddr_t are defined
>
> Also getting this linker error:
> /usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld:  
> .libs/libdbmail_la-dm_tls.o:(.bss+0x0): multiple definition of  
> `tls_context'; .libs/libdbmail_la-server.o:(.bss+0x68): first defined  
> here
>
> This is because -fno-common is now the default since GCC 10.x, and the  
> variable is implicitly declared static in both dm_tls.c >and server.c.  
> The fix is:
> --- dbmail-3.2.3/src/dm_tls.c.dist
> +++ dbmail-3.2.3/src/dm_tls.c
> @@ -31,7 +31,7 @@
> #define THIS_MODULE "tls"
>-SSL_CTX *tls_context;
> +extern SSL_CTX *tls_context;
>/* Create the initial SSL context structure */
> SSL_CTX *tls_init(void) {
>
> Finally, the wiki page for installation omits to mention libzdb is a  
> required dependency.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by fazalmajid** [comment]
Typo. It was actually 3.2.3.

**Comment by CozC** [comment]
closing.
