### ISSUE TITLE
Incomplete setup documentation for PostgreSQL

### ISSUE THREAD

**Issue by fazalmajid** [dbmail/dbmail#127]
Registration seems disabled on the wiki, so using a ticket instead.

The documentation for PostgreSQL at https://www.dbmail.org/dokuwiki/doku.php/setup_database is incomplete. In addition to:

```
psql -U dbmail dbmail < sql/postgresql/create_tables.pgsql
```

you also have to run

```
cat sql/postgresql/upgrades/*.psql|psql -U dbmail dbmail
```

otherwise dbmail fails at startup because the table `dbmail_update_steps` is missing.

**Comment by CozC** [comment]
Salve,

Thank you.

Unfortunately only the original developer (as far as a know) has the  
credentials to change/update the content at dbmail.org.
My suggestion is to add those information to the general INSTALL notes  
(https://github.com/dbmail/dbmail/blob/master/INSTALL)

Thank you.

On Tue, 15 Jun 2021 18:59:35 +0300, Fazal Majid ***@***.***>  
wrote:

>
> Registration seems disabled on the wiki, so using a ticket instead.
>
> The documentation for PostgreSQL at  
> https://www.dbmail.org/dokuwiki/doku.php/setup_database is incomplete.  
> In addition >to:
> psql -U dbmail dbmail < sql/postgresql/create_tables.pgsql
>
> you also have to run
> cat sql/postgresql/upgrades/*.psql|psql -U dbmail dbmail
>
> otherwise dbmail fails at startup because the table dbmail_update_steps  
> is missing.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Salve,

It's done,

Thank you.

On Tue, 15 Jun 2021 19:16:39 +0300, Cosmin CIORANU  
***@***.***> wrote:

> Salve,
> Thank you.
> Unfortunately only the original developer (as far as a know) has the  
> credentials to change/update the content at dbmail.org.My suggestion is  
> to add those information to the general INSTALL notes  
> (https://github.com/dbmail/dbmail/blob/master/>INSTALL)
> Thank you.
> On Tue, 15 Jun 2021 18:59:35 +0300, Fazal Majid  
> ***@***.***> wrote:
>
>>
>> Registration seems disabled on the wiki, so using a ticket instead.
>>
>> The documentation for PostgreSQL at  
>> https://www.dbmail.org/dokuwiki/doku.php/setup_database is incomplete.  
>> In >>addition to:
>> psql -U dbmail dbmail < sql/postgresql/create_tables.pgsql
>>
>> you also have to run
>> cat sql/postgresql/upgrades/*.psql|psql -U dbmail dbmail
>>
>> otherwise dbmail fails at startup because the table dbmail_update_steps  
>> is missing.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>
>
>
> --Cosmin Cioranu



-- 
Cosmin Cioranu
