### ISSUE TITLE
dbmail-users -d left some aliases

### ISSUE THREAD

**Issue by koniti** [dbmail/dbmail#129]
**cause**: in src/modules/authsql.c around line 574
`s = db_stmt_prepare(c, "DELETE FROM %saliases WHERE deliver_to=? AND lower(alias) = lower(?)",DBPFX);`

**quick hack**. to fix for MySQL (not sure it works with other DBs):
`s = db_stmt_prepare(c, "DELETE A, B FROM %saliases as A INNER JOIN %saliases as B ON B.alias = A.alias WHERE A.deliver_to=CONVERT(? , CHAR(255)) AND lower(A.alias) = lower(?)", DBPFX, DBPFX);`

**when happen**:
1. add forward address
```
dbmail-users -s forward0@other.site
dbmail-users -s forward1@other.site
+------------+-------------+---------------------+
| alias_idnr | alias       | deliver_to          |
+------------+-------------+---------------------+
|        518 | foo@bar.xxx | 1029                |
|        519 | foo@bar.xxx | forward0@other.site |
|        520 | foo@bar.xxx | forward1@other.site |
+------------+-------------+---------------------+
```

2.delete user
```
dbmail-users -d foo@bar.xxx
+------------+-------------+---------------------+
| alias_idnr | alias       | deliver_to          |
+------------+-------------+---------------------+
|        519 | foo@bar.xxx | forward0@other.site |
|        520 | foo@bar.xxx | forward1@other.site |
+------------+-------------+---------------------+
```
dbmail-users exec next, so left.
```
DELETE ..... WHERE deliver_to='1029' AND lower(alias) = lower('foo@bar.xxx')
```

**Comment by CozC** [comment]
Salve,

Nice catch.

It should work, I have to check if in postgres and sqllite the query is  
valid. We will take into consideration your sugestion.

Have a nice day.


-- 
Cosmin Cioranu

**Comment by cncioranu** [comment]
Will be ready in the next release.
