### ISSUE TITLE
Adding multiple domains

### ISSUE THREAD

**Issue by satya-500** [dbmail/dbmail#130]
adding multiple domains is not working

**Comment by CozC** [comment]
Please describe what you are doing.

Thank you.
On Mon, 27 Sep 2021 20:55:51 +0300, satya-500 ***@***.***>  
wrote:

>
> adding multiple domains is not working
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
Cosmin Cioranu

**Comment by satya-500** [comment]
Hi @CozC,
thanks fro the reply.

i wanted to add multiple domain to dbamil i.e


```
xyz@domain1.com<----------->|
xyz@domain2.com<----------->|------>mail.server.com(dbmail)
xyz@domain3.com<----------->|
``` 

so that i can use multiple domain.

**Comment by CozC** [comment]
Salve,

First you need to check if the MX-es of the domain2.com is pointing to  
this email server.
And then either use dbmail-util or manual insert into db  to insert  
***@***.*** as an alias and that's it.

After you employ the above in your DB (aliases) the information should be  
something similar as follows:

"alias_idnr" "alias" "deliver_to" "client_idnr"
"****" " ***@***.***" "****" "0"

Have a nice day.

**Comment by satya-500** [comment]
i did using following config.

```
virtual_transport = dbmail-lmtp:127.0.0.1:24
virtual_mailbox_domains = mysql:/etc/postfix/sql-virtual_mailbox_domains.cf 
virtual_mailbox_maps = mysql:/etc/postfix/sql-virtual_mailbox_maps.cf
```

**Comment by CozC** [comment]
Salve,

It is ok, but you need to make sure that your domains MX goes to this  
server, otherwise your emails will not be registered.

Also I would configure smtpd_sender_login_maps

postconf -e  
smtpd_sender_login_maps='proxy:mysql:/etc/postfix/dbmail_recipients.cf'

<file>
#nano /etc/postfix/dbmail_recipients.cf
hosts = 127.0.0.1
dbname = dbmail
user = dbmail
password = password_of_dbmail
query = SELECT alias FROM dbmail_aliases WHERE alias='%s' LIMIT 1
</file>


Have a nice day

On Tue, 28 Sep 2021 10:59:36 +0300, satya-500 ***@***.***>  
wrote:

>
> i did using following config.
> virtual_transport = dbmail-lmtp:127.0.0.1:24
> virtual_mailbox_domains =  
> mysql:/etc/postfix/sql-virtual_mailbox_domains.cfvirtual_mailbox_maps =  
> mysql:/etc/postfix/sql-virtual_mailbox_maps.cf
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
Cosmin Cioranu

**Comment by satya-500** [comment]
thanks fro the reply @CozC 

everything works fine for me, if possible can you review my config, thanks in advance 

```
# system default domain name
mydomain = xyz.com

# system hostname
myhostname = dbmail.xyz.com

# alias
alias_maps =
alias_database =

# destination settings
mydestination = localhost, localhost.localdomain, localhost
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 159.89.170.129

# relay if required
relayhost =

# general settings
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all
biff = no
compatibility_level = 2

# smtp settings
smtp_use_tls=yes
smtp_tls_security_level=may
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

#smtp deamon config
smtpd_use_tls=yes
smtpd_tls_security_level=encrypt
smtpd_banner = $myhostname ESMTP
smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
smtpd_tls_cert_file = /etc/letsencrypt/live/dbmail.xyz.com/fullchain.pem
smtpd_tls_key_file = /etc/letsencrypt/live/dbmail.xyz.com/privkey.pem
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination 


# for local
local_recipient_maps = mysql:/etc/postfix/recipient_map.cf

# for virtual domain / multiple domain
virtual_transport = dbmail-lmtp:127.0.0.1:24
virtual_mailbox_domains = mysql:/etc/postfix/sql-virtual_mailbox_domains.cf 
virtual_mailbox_maps = mysql:/etc/postfix/sql-virtual_mailbox_maps.cf


# for SASL
smtpd_sasl_auth_enable = yes
broken_sasl_auth_clients = yes
smtpd_sasl_type = cyrus
smtpd_sasl_security_options = noanonymous
smtpd_sasl_path = smtpd
smtpd_sasl_exceptions_networks = $mynetworks

```

**Comment by CozC** [comment]
Salve,

It seems that your covered everything, however I use the proxy directive  
as follows:

smtpd_sender_login_maps='proxy:mysql:/etc/postfix/dbmail_recipients.cf'
virtual_mailbox_domains='proxy:mysql:/etc/postfix/dbmail_domains.cf'
virtual_mailbox_maps='proxy:mysql:/etc/postfix/dbmail_mailboxes.cf'
proxy_read_maps='$smtpd_sender_login_maps $virtual_mailbox_domains  
$virtual_mailbox_maps $local_recipient_maps'

Also, I cannot give you a definitive answer in terms of correctness it  
should be tested "for real".

Also do not forget about:

%add /etc/postfix/master.cf if you want to use unix ports
dbmail-lmtp unix - - n - - lmtp

Also, use this doc as reference, it is nicely done:  
https://docs.iredmail.org/dbmail.mysql.centos.html#install-dbmail

have a nice day

On Tue, 28 Sep 2021 11:50:08 +0300, satya-500 ***@***.***>  
wrote:

>
> thanks fro the reply @CozC
>
> everything works fine for me, if possible can you review my config,  
> thanks in advance
> # system default domain name
> mydomain = xyz.com
>
> # system hostname
> myhostname = dbmail.xyz.com
>
> # alias
> alias_maps =
> alias_database =
>
> # destination settings
> mydestination = localhost, localhost.localdomain, localhost
> mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 159.89.170.129
>
> # relay if required
> relayhost =
>
> # general settings
> mailbox_size_limit = 0
> recipient_delimiter = +
> inet_interfaces = all
> inet_protocols = all
> biff = no
> compatibility_level = 2
>
> # smtp settings
> smtp_use_tls=yes
> smtp_tls_security_level=may
> smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
>
> #smtp deamon config
> smtpd_use_tls=yes
> smtpd_tls_security_level=encrypt
> smtpd_banner = $myhostname ESMTP
> smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated  
> defer_unauth_destination
> smtpd_tls_cert_file = /etc/letsencrypt/live/dbmail.xyz.com/fullchain.pem
> smtpd_tls_key_file = /etc/letsencrypt/live/dbmail.xyz.com/privkey.pem
> smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
> smtpd_recipient_restrictions = permit_mynetworks,  
> permit_sasl_authenticated, reject_unauth_destination
>
> # for local
> local_recipient_maps = mysql:/etc/postfix/recipient_map.cf
>
> # for virtual domain / multiple domain
> virtual_transport = dbmail-lmtp:127.0.0.1:24
> virtual_mailbox_domains =  
> mysql:/etc/postfix/sql-virtual_mailbox_domains.cfvirtual_mailbox_maps =  
> mysql:/etc/postfix/sql-virtual_mailbox_maps.cf
>
>
> # for SASL
> smtpd_sasl_auth_enable = yes
> broken_sasl_auth_clients = yes
> smtpd_sasl_type = cyrus
> smtpd_sasl_security_options = noanonymous
> smtpd_sasl_path = smtpd
> smtpd_sasl_exceptions_networks = $mynetworks
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
Cosmin Cioranu

**Comment by satya-500** [comment]
master.cf

```
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (no)    (never) (100)
# ==========================================================================
smtp      inet  n       -       y       -       -       smtpd
#smtp      inet  n       -       y       -       1       postscreen
#smtpd     pass  -       -       y       -       -       smtpd
#dnsblog   unix  -       -       y       -       0       dnsblog
#tlsproxy  unix  -       -       y       -       0       tlsproxy
submission inet n       -       y       -       -       smtpd -v
dbmail-lmtp     unix    -       -       n       -       -       lmtp -v

```

**Comment by CozC** [comment]
Seems to be ok. I would remove -v in production.

On Tue, 28 Sep 2021 12:25:11 +0300, satya-500 ***@***.***>  
wrote:

>
> master.cf
> #  
> ==========================================================================
> # service type  private unpriv  chroot  wakeup  maxproc command + args
> #               (yes)   (yes)   (no)    (never) (100)
> #  
> ==========================================================================
> smtp      inet  n       -       y       -       -       smtpd
> #smtp      inet  n       -       y       -       1       postscreen
> #smtpd     pass  -       -       y       -       -       smtpd
> #dnsblog   unix  -       -       y       -       0       dnsblog
> #tlsproxy  unix  -       -       y       -       0       tlsproxy
> submission inet n       -       y       -       -       smtpd -v
> dbmail-lmtp     unix    -       -       n       -       -       lmtp -v
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
Cosmin Cioranu

**Comment by satya-500** [comment]
thanks @CozC 

i added that **-v** for debug purpose, in production it will be removed.

**Comment by CozC** [comment]
Salve,

I hope you have solved your issues.

Enjoy.
