### ISSUE TITLE
Unable to build docker container

### ISSUE THREAD

**Issue by BobRam** [dbmail/dbmail#132]
Hi,

I am trying:

git clone https://github.com/dbmail/dbmail.git
cd dbmail
docker build .

Fail:

...
Changing password for abuild
New password:
passwd: password for abuild is unchanged
`>>>` Generating public/private rsa key pair for abuild
Enter file in which to save the key [/root/.abuild/-618574e3.rsa]: The command '/bin/sh -c adduser abuild -G abuild;     abuild-keygen -ai' returned a non-zero code: 1

How to solve?
Thanks in advance

**Comment by dguttierrez** [comment]
Hello

Open Dockerfile file and change:

abuild-keygen -ai

to 

abuild-keygen -ain

and then build again.
