### ISSUE TITLE
webhook to imap message

### ISSUE THREAD

**Issue by arstanme** [dbmail/dbmail#143]
Hi guys,
I have an account from Postmarkapp. I have already setup inbound(proper mx setups, etc tested). So whenever I receive to a certain email address, it will trigger a webhook with json and raw message contents.

Raw message sample here
`Return-Path: <maxpo01@sina.com>
Received: by p-pm-inbound03c-aws-useast1c.inbound.postmarkapp.com (Postfix, from userid 996)
	id 1119D406E5B; Sat, 22 Jan 2022 07:10:57 +0000 (UTC)
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on
	p-pm-inbound03c-aws-useast1c
X-Spam-Status: No
X-Spam-Score: 4.3
X-Spam-Tests: DEAR_SOMETHING,FREEMAIL_FROM,FREEMAIL_REPLY,FROM_MISSPACED,
	FROM_MISSP_FREEMAIL,FROM_MISSP_SPF_FAIL,RCVD_IN_DNSWL_HI,RDNS_NONE,SPF_FAIL,
	SPF_HELO_FAIL,SPOOFED_FREEMAIL,SPOOFED_FREEMAIL_NO_RDNS,TO_NO_BRKTS_FROM_MSSP,
	TO_NO_BRKTS_PCNT
Received-SPF: fail (sina.com: Sender is not authorized by default to use 'maxpo01@sina.com' in 'mfrom' identity (mechanism '-all' matched)) receiver=p-pm-inbound03c-aws-useast1c; identity=mailfrom; envelope-from="maxpo01@sina.com"; helo=sina.com; client-ip=14.23.105.186
Received: from sina.com (unknown [14.23.105.186])
	by p-pm-inbound03c-aws-useast1c.inbound.postmarkapp.com (Postfix) with ESMTP id 21849410864
	for <info@example.com>; Sat, 22 Jan 2022 07:10:51 +0000 (UTC)
From: "Sport Shirts"<maxpo01@sina.com>
To: info@example.com
Subject: Sportswear Quotation
Date: 22 Jan 2022 15:10:53 +0800
Message-ID: <20220122151053.8E9E0C5A8DF2AA76@sina.com>
MIME-Version: 1.0
Content-Type: text/plain
Content-Transfer-Encoding: 8bit

My message`

So, my question is - can I feed dbmail-deliver with this and get it delivered to an account?

**Comment by alan-hicks** [comment]
Hi Arstanme,

Try it and see. "It worked for me(tm)"

dbmail-deliver needs an email and if that's an email, it will be delivered.

Regards,
Alan

**Comment by arstanme** [comment]
Hi Alan,
thanks for the reply. I'm trying to set it up and run on Ubuntu 20.04 - compiled successfully but I got stuck at configuring. Is there documentation, tutorials I can refer to?
Man pages not entirely helping. The information that I found googling is either obsolete or not full

**Comment by CozC** [comment]
Salve,

Unfortunately there is not so much documentation available. The dbmail.org  
was source of inspiration but now it just redirects to the github part.

So,
I never confgured via dbmail-deliver, I allways use postfix via  
dbmail-lmtp, it works nice enough but is kinda slow on import (migration).
However I found something that might help you  
http://innerlife.io/dbmail-postgresql-postfix-sasl-debian-part3/ which  
seems to be close enough.

Hope it helps.

On Sat, 22 Jan 2022 16:22:22 +0200, arstanme ***@***.***>  
wrote:

>
> Hi Alan,
> thanks for the reply. I'm trying to set it up and run on Ubuntu 20.04 -  
> compiled successfully but I got stuck at configuring. Is >there  
> documentation, tutorials I can refer to?
> Man pages not entirely helping. The information that I found googling is  
> either obsolete or not full
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.You  
> are receiving this because you are subscribed to this thread.



-- 
Cosmin Cioranu

**Comment by alan-hicks** [comment]
Hi arstanme,

If you mean configuring etc/dbmail.conf, there's not much to it, mainly 
specify the database (dburi) and authentication via sql or ldap 
(authdriver). If you're using tls you need to add the tls_* entries. The 
dburi is as per http://www.tildeslash.com/libzdb/

If you're looking for how to send emails from your mta to dbmail then 
it's that system that needs configuring. If you're using Exim as your 
mta then XML Team recently sponsored me to write some documentation 
https://github.com/dbmail/dbmail/blob/master/contrib/exim-dbmail-configure

Alan
