### ISSUE TITLE
dbmail-httpd: create/delete users via API

### ISSUE THREAD

**Issue by le-kazankin** [dbmail/dbmail#145]
Hello

HTTP request to dmail-httpd (curl -v user:pass@dbmail-server:10081/users/ -XPOST -d 'create=httpuser%40example.ru&password="pass"&encoding=utf-8&quota=100') don't create user in PostgreSQL DB. 
But records about the creation of a user in the dbmail.log are actually exist.
There is no INSERT or UPDATE in pgsql.log

What am I doing wrong?

![image](https://user-images.githubusercontent.com/88597608/151962579-4a5ff4d1-b7be-48bc-82b9-b8d2dda422ed.png)
![image](https://user-images.githubusercontent.com/88597608/151962735-851e02e9-f691-48fa-a3a8-ec2eb511ab8d.png)

**Comment by CozC** [comment]
Salve,Please make sure the auth driver is authsql.Also, if we find an issue, you can use sql to create an user. If it is an acceptable workaround, we will gladly provide one for you.Thank you.CC @ gmail
-------- Original message --------From: le-kazankin ***@***.***> Date: 2/1/22  14:15  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Subscribed ***@***.***> Subject: [dbmail/dbmail] dbmail-httpd: create/delete users via API (Issue #145) 
Hello
HTTP request to dmail-httpd (curl -v ***@***.***:10081/users/ -XPOST -d 'create=httpuser%40example.ru&password="pass"&encoding=utf-8&quota=100') don't create user in PostgreSQL DB.
But records about the creation of a user in the dbmail.log are actually exist.
There is no INSERT or UPDATE in pgsql.log
What am I doing wrong?

**Comment by arstanme** [comment]
Hi,
where can I find docs for API?

> Hello
> 
> HTTP request to dmail-httpd (curl -v user:pass@dbmail-server:10081/users/ -XPOST -d 'create=httpuser%40example.ru&password="pass"&encoding=utf-8&quota=100') don't create user in PostgreSQL DB. But records about the creation of a user in the dbmail.log are actually exist. There is no INSERT or UPDATE in pgsql.log
> 
> What am I doing wrong?
> 
> ![image](https://user-images.githubusercontent.com/88597608/151962579-4a5ff4d1-b7be-48bc-82b9-b8d2dda422ed.png) ![image](https://user-images.githubusercontent.com/88597608/151962735-851e02e9-f691-48fa-a3a8-ec2eb511ab8d.png)

**Comment by le-kazankin** [comment]
> Please make sure the auth driver is authsql.

In my configuration, the following setting is set: "authdriver =sql" in [DBMAIL]. 
Setting a similar parameter in the HTTP section and restart dbmail-httpd did not help.
dbmail-util successfully creates users, the problem is only with dbmail-httpd.
Installed version of dbmail-httpd is 3.2.3

![image](https://user-images.githubusercontent.com/88597608/152698996-5c072d80-7ade-42ef-89dc-f5d2a7cc9cfb.png)

**Comment by le-kazankin** [comment]
I tried to find api requests using this old phpclient: https://github.com/dbmail/dbmail/blob/3dd7f9cd06bf64636573a0e2a23572a5ba38cfc1/contrib/dbmailclient.php
Some API request examples can be found there: https://github.com/dbmail/dbmail/blob/3dd7f9cd06bf64636573a0e2a23572a5ba38cfc1/doc/README.http


> Hi, where can I find docs for API?
> 
> > Hello
> > HTTP request to dmail-httpd (curl -v user:pass@dbmail-server:10081/users/ -XPOST -d 'create=httpuser%40example.ru&password="pass"&encoding=utf-8&quota=100') don't create user in PostgreSQL DB. But records about the creation of a user in the dbmail.log are actually exist. There is no INSERT or UPDATE in pgsql.log
> > What am I doing wrong?
> > ![image](https://user-images.githubusercontent.com/88597608/151962579-4a5ff4d1-b7be-48bc-82b9-b8d2dda422ed.png) ![image](https://user-images.githubusercontent.com/88597608/151962735-851e02e9-f691-48fa-a3a8-ec2eb511ab8d.png)

**Comment by cypa** [comment]
there is PostgREST already - have anybody tested it?

**Comment by CozC** [comment]
If you are asking about the implementation using as backend the Postresql database server is production ready, then the answer is yes. 
-------- Original message --------From: cypa ***@***.***> Date: 7/13/22  08:51  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Cosmin Cioranu ***@***.***>, Comment ***@***.***> Subject: Re: [dbmail/dbmail] dbmail-httpd: create/delete users via API (Issue #145) 
there is PostgREST already - have anybody tested it?

**Comment by CozC** [comment]
But, in the case of postgREST, I do not  believe is in the scope of dbmail. 
-------- Original message --------From: cypa ***@***.***> Date: 7/13/22  08:51  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Cosmin Cioranu ***@***.***>, Comment ***@***.***> Subject: Re: [dbmail/dbmail] dbmail-httpd: create/delete users via API (Issue #145) 
there is PostgREST already - have anybody tested it?

**Comment by cypa** [comment]
thank you, 
I shall test it soon

**Comment by CozC** [comment]
Please post your conclussions into this thread to be seen by others. Thank you
-------- Original message --------From: cypa ***@***.***> Date: 7/13/22  09:35  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Cosmin Cioranu ***@***.***>, Comment ***@***.***> Subject: Re: [dbmail/dbmail] dbmail-httpd: create/delete users via API (Issue #145) 
thank you,
I shall test it soon
