### ISSUE TITLE
Volunteers for dbmail documentation project

### ISSUE THREAD

**Issue by arstanme** [dbmail/dbmail#147]
Do you need volunteers for dbmail documentation?

I'm willing to put some hours for it. I'm sure there will be more people joining along the way.

**Comment by CozC** [comment]
Salve,It would be nice, i can a share my docs, they are based on postfix integrations. Maybe on wiki ***@***.*** ? CC @ gmail
-------- Original message --------From: arstanme ***@***.***> Date: 2/22/22  15:31  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Subscribed ***@***.***> Subject: [dbmail/dbmail] Volunteers for dbmail documentation project (Issue #147) 
Do you need volunteers for dbmail documentation?
I'm willing to put some hours for it. I'm sure there will be more people joining along the way.

**Comment by arsenico13** [comment]
Documentation for this project would be awesome.
I just found this repo while doin' some googling and It's not very straightforward where to begin :D
(or maybe it's just me... 🤷)

**Comment by webtech09** [comment]
:) maybe you can create documentation from this. i having trouble to install this

**Comment by CozC** [comment]
Salve,

DBMail is a backend storage and method to access your emails (via  
IMAP/POP3). The emails are sent to this store via lmtp (there is another  
solution but a little bit more complicate to setup (my opinion)
In front of DBMail you can put whatever MTA (e.g. postfix) that supports  
lmtp to transfer emails .

Happy configuring.

Related to the documentation we are always happy to accept people to do it.

PS: I can give you info related to postfix-dbmail-mariadb only, others may  
have other setups.

-- 
Cosmin Cioranu

**Comment by alan-hicks** [comment]
https://dbmail.org has been greatly expanded and reorganized to make it easier to understand dbmail from all perspectives including SysAdmins, users and contributors.
