### ISSUE TITLE
IMAP Fetch subject line bad encoding

### ISSUE THREAD

**Issue by bajizs** [dbmail/dbmail#149]
I don't known why.... I have more servers, identical dbmail version (3.2.6), but on one server when we fetch IMAP messages with special chars it is not encoded as iso-8859-1. I don't known what is the differrencies, checked config files, version, libgmime version.... Only differences is that one serevr is on Opensuse 15.3 (bad) and one another is on Opensuse  15.2.

Example
OK Server:

* OK [CAPABILITY IMAP4rev1 AUTH=LOGIN AUTH=CRAM-MD5 STARTTLS ID LITERAL+] dbmail 3.2.6 ready.
A1 login *********** ***********

A1 OK [CAPABILITY IMAP4rev1 ACL RIGHTS=texk NAMESPACE CHILDREN SORT QUOTA THREAD=ORDEREDSUBJECT UNSELECT IDLE STARTTLS ID UIDPLUS WITHIN LOGINDISABLED CONDSTORE LITERAL+ ENABLE QRESYNC] User ********* authenticated
g21 SELECT "INBOX"
* 8 EXISTS
* 0 RECENT
* FLAGS (\Seen \Answered \Deleted \Flagged \Draft Junk NonJunk)
* OK [PERMANENTFLAGS (\Seen \Answered \Deleted \Flagged \Draft Junk NonJunk \*)] Flags allowed.
* OK [UIDNEXT 3307004] Predicted next UID
* OK [UIDVALIDITY 156] UID value
* OK [HIGHESTMODSEQ 244] Highest
g21 OK [READ-WRITE] SELECT completed
a1 FETCH 1:* (FLAGS BODY[HEADER.FIELDS (SUBJECT DATE FROM)])
* 1 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {61}
Subject: TEST MAIL
Date: Tue, 11 May 2021 09:59:25 +0200

)
* 2 FETCH (FLAGS (\Seen Junk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {57}
Subject: TEST2
Date: Tue, 11 May 2021 10:00:13 +0200

)
* 3 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {61}
Subject: TEST MEEE
Date: Tue, 22 Jun 2021 14:04:36 +0200

)
* 4 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {70}
Subject: TEST mail Vacation
Date: Tue, 22 Jun 2021 17:11:30 +0200

)
* 5 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {62}
Subject: TEST again
Date: Tue, 22 Jun 2021 17:16:17 +0200

)
* 6 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {75}
Subject: Re: Out of office reply
Date: Tue, 22 Jun 2021 17:20:00 +0200

)
* 7 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {61}
Subject: TETS mail
Date: Tue, 22 Jun 2021 17:25:08 +0200

)
* 8 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {81}
Subject: =?iso-8859-1?b?6eHp4eHp/PM=?=
Date: Sat, 30 Apr 2022 18:06:59 +0200

)
a1 OK FETCH completed

BAD Server:
* OK [CAPABILITY IMAP4rev1 AUTH=LOGIN AUTH=CRAM-MD5 STARTTLS ID LITERAL+] dbmail 3.2.6 ready.
A1 login ***** **********
A1 OK [CAPABILITY IMAP4rev1 ACL RIGHTS=texk NAMESPACE CHILDREN SORT QUOTA THREAD=ORDEREDSUBJECT UNSELECT IDLE STARTTLS ID UIDPLUS WITHIN LOGINDISABLED CONDSTORE LITERAL+ ENABLE QRESYNC] User ******** authenticated
g21 SELECT "INBOX"
* 2 EXISTS
* 0 RECENT
* FLAGS (\Seen \Answered \Deleted \Flagged \Draft NonJunk)
* OK [PERMANENTFLAGS (\Seen \Answered \Deleted \Flagged \Draft NonJunk \*)] Flags allowed.
* OK [UIDNEXT 10964871] Predicted next UID
* OK [UIDVALIDITY 4922] UID value
* OK [HIGHESTMODSEQ 9] Highest
g21 OK [READ-WRITE] SELECT completed
a1 FETCH 1:* (FLAGS BODY[HEADER.FIELDS (SUBJECT DATE FROM)])
* 1 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {72}
Subject: �kezetek pr�ba ��?�?
Date: Tue, 26 Apr 2022 09:00:40 +0200

)
* 2 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {55}
Subject: ��?
Date: Sat, 30 Apr 2022 18:05:32 +0200

)
a1 OK FETCH completed

**Comment by CozC** [comment]
Salve,

Those conversions are made via ;ibgmime 2.6 which might be dependent on  
some system configuration (it is a big maybe).
I would consider checking, also, the default charset (and collation) of  
the datebase (or connection to the database).





On Sat, 30 Apr 2022 19:49:48 +0300, Baji Zsolt ***@***.***>  
wrote:

>
> I don't known why.... I have more servers, identical dbmail version  
> (3.2.6), but on one server when we fetch IMAP messages with special  
> chars it is not >encoded as iso-8859-1. I don't known what is the  
> differrencies, checked config files, version, libgmime version.... Only  
> differences is that one serevr is >on Opensuse 15.3 (bad) and one  
> another is on Opensuse 15.2.
>
> Example
> OK Server:
> OK [CAPABILITY IMAP4rev1 AUTH=LOGIN AUTH=CRAM-MD5 STARTTLS ID LITERAL+]  
> dbmail 3.2.6 ready.
> A1 login *********** ***********
>
> A1 OK [CAPABILITY IMAP4rev1 ACL RIGHTS=texk NAMESPACE CHILDREN SORT  
> QUOTA THREAD=ORDEREDSUBJECT UNSELECT IDLE >STARTTLS ID UIDPLUS WITHIN  
> LOGINDISABLED CONDSTORE LITERAL+ ENABLE QRESYNC] User *********  
> authenticated
> g21 SELECT "INBOX"
> 8 EXISTS
> 0 RECENT
> FLAGS (\Seen \Answered \Deleted \Flagged \Draft Junk NonJunk)
> OK [PERMANENTFLAGS (\Seen \Answered \Deleted \Flagged \Draft Junk  
> NonJunk *)] Flags allowed.
> OK [UIDNEXT 3307004] Predicted next UID
> OK [UIDVALIDITY 156] UID value
> OK [HIGHESTMODSEQ 244] Highest
> g21 OK [READ-WRITE] SELECT completed
> a1 FETCH 1:* (FLAGS BODY[HEADER.FIELDS (SUBJECT DATE FROM)])
> 1 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)]  
> {61}
> Subject: TEST MAIL
> Date: Tue, 11 May 2021 09:59:25 +0200
>
> )
> 2 FETCH (FLAGS (\Seen Junk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)] {57}
> Subject: TEST2
> Date: Tue, 11 May 2021 10:00:13 +0200
>
> )
> 3 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)]  
> {61}
> Subject: TEST MEEE
> Date: Tue, 22 Jun 2021 14:04:36 +0200
>
> )
> 4 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)]  
> {70}
> Subject: TEST mail Vacation
> Date: Tue, 22 Jun 2021 17:11:30 +0200
>
> )
> 5 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)]  
> {62}
> Subject: TEST again
> Date: Tue, 22 Jun 2021 17:16:17 +0200
>
> )
> 6 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)]  
> {75}
> Subject: Re: Out of office reply
> Date: Tue, 22 Jun 2021 17:20:00 +0200
>
> )
> 7 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)]  
> {61}
> Subject: TETS mail
> Date: Tue, 22 Jun 2021 17:25:08 +0200
>
> )
> 8 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)]  
> {81}
> Subject: =?iso-8859-1?b?6eHp4eHp/PM=?=
> Date: Sat, 30 Apr 2022 18:06:59 +0200
>
> )
> a1 OK FETCH completed
>
> BAD Server:
> OK [CAPABILITY IMAP4rev1 AUTH=LOGIN AUTH=CRAM-MD5 STARTTLS ID LITERAL+]  
> dbmail 3.2.6 ready.
> A1 login ***** **********
> A1 OK [CAPABILITY IMAP4rev1 ACL RIGHTS=texk NAMESPACE CHILDREN SORT  
> QUOTA THREAD=ORDEREDSUBJECT UNSELECT >IDLE STARTTLS ID UIDPLUS WITHIN  
> LOGINDISABLED CONDSTORE LITERAL+ ENABLE QRESYNC] User ********  
> authenticated
> g21 SELECT "INBOX"
> 2 EXISTS
> 0 RECENT
> FLAGS (\Seen \Answered \Deleted \Flagged \Draft NonJunk)
> OK [PERMANENTFLAGS (\Seen \Answered \Deleted \Flagged \Draft NonJunk *)]  
> Flags allowed.
> OK [UIDNEXT 10964871] Predicted next UID
> OK [UIDVALIDITY 4922] UID value
> OK [HIGHESTMODSEQ 9] Highest
> g21 OK [READ-WRITE] SELECT completed
> a1 FETCH 1:* (FLAGS BODY[HEADER.FIELDS (SUBJECT DATE FROM)])
> 1 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)]  
> {72}
> Subject: �kezetek pr�ba ��?�?
> Date: Tue, 26 Apr 2022 09:00:40 +0200
>
> )
> 2 FETCH (FLAGS (\Seen NonJunk) BODY[HEADER.FIELDS (SUBJECT DATE FROM)]  
> {55}
> Subject: ��?
> Date: Sat, 30 Apr 2022 18:05:32 +0200
>
> )
> a1 OK FETCH completed
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.



-- 
Cosmin Cioranu

**Comment by bajizs** [comment]
Database is mysql, converted to utf8mb4 (befor was utf8 but was identical problem, database conversion not solves it). Collation: utf8mb4_general_ci

dbmail.conf on both server;
encoding             = utf8
default_msg_encoding = utf8

mysql verzion:
10.5.15-MariaDB on problematic server
10.4.17-MariaDB on OK server.

Mysql setup on both server only innodb optimization (memory pool...)

Some other information: problem is only when fetching the header information (listing mails in folder), when reading full mail, header comes correctly like  "Subject: =?UTF-8?B?VEVTWlQgxZHDusWxw7bDvMOzw6nDoQ==?="

If you use some mail client (webmail, or installed Outlook/Thunderbird), when list emails in folder, You can't see correct Subject, but when open it, everything is correct. This is very frustrating for users and me, because I don't know what is misconfigured...

**Comment by CozC** [comment]
I found this: https://mariadb.com/kb/en/unicode/

I guess utf8 is wrong in 10.5 (in this case) and it behaves differently  
then in 10.4, i guess it should be utf8mb4.

On Sat, 30 Apr 2022 23:06:07 +0300, Baji Zsolt ***@***.***>  
wrote:

>
> Database is mysql, converted to utf8mb4 (befor was utf8 but was  
> identical problem, database conversion not solves it). Collation:  
> utf8mb4_general_ci
>
> dbmail.conf on both server;
> encoding = utf8
> default_msg_encoding = utf8
>
> mysql verzion:
> 10.5.15-MariaDB on problematic server
> 10.4.17-MariaDB on OK server.
>
> Mysql setup on both server only innodb optimization (memory pool...)
>
> Some other information: problem is only when fetching the header  
> information (listing mails in folder), when reading full mail, header  
> comes correctly like >"Subject:  
> =?UTF-8?B?VEVTWlQgxZHDusWxw7bDvMOzw6nDoQ==?="
>
> If you use some mail client (webmail, or installed Outlook/Thunderbird),  
> when list emails in folder, You can't see correct Subject, but when open  
> it, >everything is correct. This is very frustrating for users and me,  
> because I don't know what is misconfigured...
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.



-- 
Cosmin Cioranu

**Comment by bajizs** [comment]
If I set in dbmail.conf
encoding = utf8mb4


thre result is segfault:
 dbmail/imap4d[17935]: EMERGENCY:[iconv] dbmail_iconv_once(+65): iconv failure

Broadcast message from systemd-journald@mail (Sat 2022-04-30 22:19:57 CEST):

dbmail/imap4d[17935]: EMERGENCY:[iconv] dbmail_iconv_once(+65): iconv failure

Apr 30 22:19:57 mail dbmail/imap4d[17935]: EMERGENCY:[iconv] dbmail_iconv_once(+65): iconv failure
Apr 30 22:20:00 mail dbmail/imap4d[17935]: Alert:[libzdb] TabortHandler(+45): AssertException: P
                                            raised in ConnectionPool_getConnection at src/db/ConnectionPool.c:322
Apr 30 22:20:00 mail kernel: dbmail-imapd[17935]: segfault at 58 ip 00007fcdc258a0d0 sp 00007fff32d8baf8 error 4 in libpthread-2.31.so[7fcdc257d000+1e000]
Apr 30 22:20:00 mail kernel: Code: f8 fc 0f 8c ae fe ff ff 83 f8 fd 7e 97 83 c0 01 74 92 e9 9f fe ff ff 0f 1f 00 90 90 90 90 90 90 90 90 90 90 90 90 90 90 90 90 <8b> 47 10 89 c2 81 e2 7f 01 00 00 90 83 e0 7c 0f 85 93 00 00 00 55

**Comment by CozC** [comment]
So the issue is related to issue #108 ?

On Sat, 30 Apr 2022 23:22:02 +0300, Baji Zsolt ***@***.***>  
wrote:

>
> If I set in dbmail.conf
> encoding = utf8mb4
>
> thre result is segfault:
> dbmail/imap4d[17935]: EMERGENCY:[iconv] dbmail_iconv_once(+65): iconv  
> failure
>
> Broadcast message from ***@***.*** (Sat 2022-04-30 22:19:57  
> CEST):
>
> dbmail/imap4d[17935]: EMERGENCY:[iconv] dbmail_iconv_once(+65): iconv  
> failure
>
> Apr 30 22:19:57 mail dbmail/imap4d[17935]: EMERGENCY:[iconv]  
> dbmail_iconv_once(+65): iconv failure
> Apr 30 22:20:00 mail dbmail/imap4d[17935]: Alert:[libzdb]  
> TabortHandler(+45): AssertException: P
> raised in ConnectionPool_getConnection at src/db/ConnectionPool.c:322
> Apr 30 22:20:00 mail kernel: dbmail-imapd[17935]: segfault at 58 ip  
> 00007fcdc258a0d0 sp 00007fff32d8baf8 error 4 in  
> libpthread-2.31.so>[7fcdc257d000+1e000]
> Apr 30 22:20:00 mail kernel: Code: f8 fc 0f 8c ae fe ff ff 83 f8 fd 7e  
> 97 83 c0 01 74 92 e9 9f fe ff ff 0f 1f 00 90 90 90 90 90 90 90 90 90 90  
> 90 90 90 90 90 90 <8b> >47 10 89 c2 81 e2 7f 01 00 00 90 83 e0 7c 0f 85  
> 93 00 00 00 55
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.



-- 
Cosmin Cioranu

**Comment by alan-hicks** [comment]
encoding = utf8 is correct as utf8mb4 is for storage

**Comment by alan-hicks** [comment]
Hello,

I've started looking at this, alas it's a complex area and doubt there 
will be an easy fix.

You might like to check:

  * the locale of the dbmail user, there may be different users for
    dbmail-deliver and dbmail-imapd;
  * the default database locale;
  * version of iconv.

Alan

**Comment by bajizs** [comment]
>  * the locale of the dbmail user, there may be different users for
>     dbmail-deliver and dbmail-imapd;

Not relevant, created system user for dbmail processes, all process work over it (use lmtp). And not only new email have bad encoding, old (befor system upgrade) have too. On both server the dbmail users local is utf8:

sudo -u dbmail locale charmap
UTF-8


>   * the default database locale;
Identical on both server:

show variables like '%character%';
+--------------------------+------------------------------+
| Variable_name            | Value                        |
+--------------------------+------------------------------+
| character_set_client     | utf8                         |
| character_set_connection | utf8                         |
| character_set_database   | utf8mb4                      |
| character_set_filesystem | binary                       |
| character_set_results    | utf8                         |
| character_set_server     | utf8mb4                      |
| character_set_system     | utf8                         |
| character_sets_dir       | /usr/share/mariadb/charsets/ |
+--------------------------+------------------------------+


>   * version of iconv.

On old server:
iconv (GNU libc) 2.26

On new server:
iconv (GNU libc) 2.31



If I have time, then I will install an VPS with Opensuse 15.2 and I will connect to this "new" database, or try to connect dbmail-imap from old server to newer database. Maybe this will answer to question where is the problem: iconv or database version.... Problem is that both system is in production...

**Comment by CozC** [comment]
Salve Baji,The DBMail and database are hosted on the same vm/host? There is no need to provide such a machine (issues related to gdpr may arise). We will try to recrete the environment and check the issue. CC @ gmail
-------- Original message --------From: Baji Zsolt ***@***.***> Date: 5/1/22  21:54  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Cosmin Cioranu ***@***.***>, Comment ***@***.***> Subject: Re: [dbmail/dbmail] IMAP Fetch subject line bad encoding (Issue #149) 


the locale of the dbmail user, there may be different users for
dbmail-deliver and dbmail-imapd;


Not relevant, created system user for dbmail processes, all process work over it (use lmtp). And not only new email have bad encoding, old (befor system upgrade) have too. On both server the dbmail users local is utf8:
sudo -u dbmail locale charmap
UTF-8


the default database locale;
Identical on both server:


show variables like '%character%';
+--------------------------+------------------------------+
| Variable_name            | Value                        |
+--------------------------+------------------------------+
| character_set_client     | utf8                         |
| character_set_connection | utf8                         |
| character_set_database   | utf8mb4                      |
| character_set_filesystem | binary                       |
| character_set_results    | utf8                         |
| character_set_server     | utf8mb4                      |
| character_set_system     | utf8                         |
| character_sets_dir       | /usr/share/mariadb/charsets/ |
+--------------------------+------------------------------+


version of iconv.


On old server:
iconv (GNU libc) 2.26
On new server:
iconv (GNU libc) 2.31
If I have time, then I will install an VPS with Opensuse 15.2 and I will connect to this "new" database, or try to connect dbmail-imap from old server to newer database. Maybe this will answer to question where is the problem: iconv or database version.... Problem is that both system is in production...

**Comment by bajizs** [comment]
I have tested mysql and dbmail the server with older system (Opensuse 15.2). Connected dbmail from this old server to database of new server (on Opensuse 15.3). Result was identical, this says that the problem is on database level.

And afte detailed analysing I have found solution. Everything is in cofiguration of dburi database connection.

If You setup connection as:
dburi                = mysql://username:password@localhost:3306/dbmail

dbmail will connect to database as an character set predefined (somewhere) what isn't always utf8.

If You define conenction as:
dburi                = mysql://localhost:3306/dbmail?charset=utf8&user=username&password=password

than dbmail connection pool will always use utf8 as connection charset, and everything will work correctly.

For anyone who has similar problem only is required te reformat dburi parameter in dbmail.conf. Pleas add this info in documentation.

I don't know what modifies encoding = utf8  in dbmail.conf, but this don't have effect on database connection character set only on iconv - I think. Maybe in next release can be correct this behavior. For example when dbmail connect to database, it set up charset to use identical what is defined in "encoding" parameter.

Thank everybody for all suggestion and information.

**Comment by CozC** [comment]
Salve,

Nicely done. Thank you, we will check the issue and see what has to be  
changed.
I have done a quick check, when dburi is used, encoding somehow is  
skipped. Encoding was used in older way of connecting to db. That will be  
fixed.

-- 
Cosmin Cioranu
