### ISSUE TITLE
www.dbmail.org is down?

### ISSUE THREAD

**Issue by hemml** [dbmail/dbmail#150]
Cannot reach http://www.dbmail.org, is it temporary problem?
Is the project still alive?

**Comment by CozC** [comment]
Salve,

Only the dbmail.org is down, the project is still alive, a few of us are  
maintaining it on github. The org domain has not been transfered to the  
maintainers of dbmail on github.

Have a nice day.
-- 
Cosmin Cioranu

**Comment by hemml** [comment]
Ok, thank you for you efforts!
