### ISSUE TITLE
dbmail-imap crash

### ISSUE THREAD

**Issue by hemml** [dbmail/dbmail#159]
The following python script leads to dbmail-imap crash without any disgnostics:

import imaplib
M = imaplib.IMAP4_SSL("imap-server")
M.login("username", "password")
M.append("INBOX",None,None,"From xxx@aaa.yyy\r\n")

**Comment by alan-hicks** [comment]
Thanks for the report.
I'm able to reproduce this so will investigate and work on a fix.

**Comment by alan-hicks** [comment]
Thanks for the report.
I'm able to reproduce this so will investigate and work on a fix.

**Comment by hemml** [comment]
I'm also catching a crash with wrong formatted date parameter in APPEND, now trying to find a minimal working example.
In this case the error log is following:

```
Jun 04 20:17:20 b1f313c4a3c9 dbmail-imapd[8]: [0x5559aacae0a0] Error:[message] _header_value_get_id(+1583): SQLException: ERROR:  timestamp out of range: "4459332-10-09"
CONTEXT:  unnamed portal parameter $4 = '...'
malloc_consolidate(): invalid chunk size
```
And docker log output:
```
imap           | Aborted
imap exited with code 134
```

**Comment by hemml** [comment]
Now it don't crashed, thanks a lot!
BTW, is there a way to quickly migrate a lot of mail from .mbox format do dbmail?
I have tried a dbmail-deliver (with python script from the contrib) and my custom script which uses IMAP (and stomped into this issue while debugging), but in both case transfer rate is slow. With IMAP connection I can append small messages for 0.6-0.7 sec each. It is too slow, because I'm migrating a whole server with ~200 users with lot of mail. I'm planning to use a pool of parallel connections to speedup the import, but, may be, there is a way to put messages directly to the database?

**Comment by CozC** [comment]
Take a look at dbmail-deliver. CC @ gmail
-------- Original message --------From: hemml ***@***.***> Date: 6/8/22  16:55  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Cosmin Cioranu ***@***.***>, Comment ***@***.***> Subject: Re: [dbmail/dbmail] dbmail-imap crash (Issue #159) 
Now it don't crashed, thanks a lot!
BTW, is there a way to quickly migrate a lot of mail from .mbox format do dbmail?
I have tried a dbmail-deliver (with python script from the contrib) and my custom script which uses IMAP (and stomped into this issue while debugging), but in both case transfer rate is slow. With IMAP connection I can append small messages for 0.6-0.7 sec each. It is too slow, because I'm migrating a whole server with ~200 users with lot of mail. I'm planning to use a pool of parallel connections to speedup the import, but, may be, there is a way to put messages directly to the database?

**Comment by alan-hicks** [comment]
For bulk loads you might like to look at dbmail-lmtpd.
Storing emails in the database is fairly complex and best avoided except through the dbmail apps. Some work has been done by others on optimising reads for web clients, but none I'm aware of for inserts.

**Comment by hemml** [comment]
Thank you for the recommendation!
Unfortunately, I have to import existing users mail, preserving message flags (which are stored, btw, in non-standary way iin .mbox files). I have looked into dbmail sources and find a way to do this by calling `sort_deliver_to_mailbox(...)`, but IMAP method seems to be easier to implement. With 30 concurent connections I can achieve about 1000 msg/min speed (processor load is not so high during this, so it is I/O limit of my system, I think), which is enough for me. 

BTW, some user messages had a `\0` symbols and dbmail rejected them. Not sure, this is violating standards or not, but funny fact, huh.

**Comment by alan-hicks** [comment]
Congratulations on your edge cases, null terminated strings are everywhere so not sure how I would approach those. Hope you don't have too many.

**Comment by hemml** [comment]
We have not so many messages with `\0`, all of them a very old (2004, 2007 years), so this is not a big problem.

Also, I found a possible race condition -- after creating a folder, I'm starting to fill it using 30 imap connections to 5 daemons. Sometimes, some of `APPEND` commands returns `permission deny` error, I think, it is because `CREATE` command reports `OK` before all ACLs are really set. I have fixed that just by retrying appends after `permission deny` error.

I don't thinks this is a security issue, because no ACL means deny, but may be there are some more race conditions exists.

**Comment by hemml** [comment]
upd: it seems, what `permission deny` sometimes returned even while appending to `INBOX`. The filling process started normally, but after some number of messages all servers started to respond with `permission deny` after 1-2 appends. I'm reconnecting after the first `permission deny` error, but in new connection the error appears again after 1-2 appends. May be this is a bug.

**Comment by alan-hicks** [comment]
Is there a debug log that might offer insight?
It might be worth checking memory usage, a memory leak might cause this.
Does restarting the imapd service fix the issue?

**Comment by hemml** [comment]
I see nothing special in the log, even with 511 level. The problem exists even if I'm using multiple (20) connections to the single imap server. But, the problem is gone if I'm removing flags (`\Seen`, `\Answered`, etc) from `APPEND`.  Trying to investigate more.

**Comment by hemml** [comment]
I have found a root of the problem -- I'm appeninng messages without `select` of the folder first (the specification allow this) and _sometimes_ `append` returns `permission deny` error on high load if message flags are specefied. If I perform `select` first -- all works fine.

**Comment by CozC** [comment]
Thank you for the report, we will take a look. CC @ gmail
-------- Original message --------From: hemml ***@***.***> Date: 6/4/22  16:56  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Subscribed ***@***.***> Subject: [dbmail/dbmail] dbmail-imap crash (Issue #159) 
The following python script leads to dbmail-imap crash without any disgnostics:
import imaplib
M = imaplib.IMAP4_SSL("imap-server")
M.login("username", "password")
M.append("INBOX",None,None,"From ***@***.***\r\n")

**Comment by CozC** [comment]
Can you provide an working example with wrong date on append? CC @ gmail
-------- Original message --------From: hemml ***@***.***> Date: 6/4/22  20:23  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [dbmail/dbmail] dbmail-imap crash (Issue #159) 
I'm also catching a crash with wrong formatted date parameter in APPEND, now trying to find a minimal working example.
In this case the error log is following:
Jun 04 20:17:20 b1f313c4a3c9 dbmail-imapd[8]: [0x5559aacae0a0] Error:[message] _header_value_get_id(+1583): SQLException: ERROR:  timestamp out of range: "4459332-10-09"
CONTEXT:  unnamed portal parameter $4 = '...'
malloc_consolidate(): invalid chunk size

And docker log output:
imap           | Aborted
imap exited with code 134

**Comment by hemml** [comment]
The date-specific problems are solved in the current branch, the append-without-select may be not, but now I have already finished my huge mail import and cannot check it again.
