### ISSUE TITLE
I have installed DBmail and created MX records yet not able to find mail in MySQL

### ISSUE THREAD

**Issue by rebootcode** [dbmail/dbmail#16]
I have just installed dbmail and have configured MX records and A records for Mail. I have even imported the MySQL database of dbmail.

I created "user" using "`dbmail-user`" and sent a test mail to the created mail account.

But I am not able to find any mail message in the database. Even when I export mail for the user, it is empty as well.

Where is mail stored? Have I missed any step?

- dbmail installed
- postfix installed and configured
- database of dbmail imported
- user-created using `dbmail-user`
- MX record and A record configured for the domain name to the server
- ping test for domain record successful
- Sent test mail to created email account.

=> Waited for 2 hour ( no mail available )

Have I missed any step?

**Comment by langemeijer** [comment]
This is not an issue with the dbmail project. Please inspect your servers' logs for any clues to solve your problem. If you're certain you've tried everything, you might find community support on the user mailinglist: http://dbmail.org/index.php?page=mailinglists
