### ISSUE TITLE
DBMail-Users - user delete wrong SQL Syntax on latest MySQL

### ISSUE THREAD

**Issue by skeyby** [dbmail/dbmail#18]
Latest MySQL are a bit more strict about type checking in queries.

Dbmail-users -d generates the following query:

`DELETE FROM dbmail_aliases WHERE deliver_to=37949 AND lower(alias) = lower('all@xxxxxxx.it');`

This causes the following error

Error 'Truncated incorrect DOUBLE value: 'info@schema31.it'' on query. Default database: 'dbmail'. Query: 'DELETE FROM dbmail_aliases WHERE deliver_to=37949 AND lower(alias) = lower('all@xxxxxxxx.it')'

Since deliver_to is a String, the correct query is:

`DELETE FROM dbmail_aliases WHERE deliver_to='37949' AND lower(alias) = lower('all@xxxxxxx.it');`

**Comment by CozC** [comment]
Given the issue that will bring other updates mostly on all actions related to deliver_to. 
It will be marked as bug and hopefully we will be seeing an update soon.
