### ISSUE TITLE
Does Postgresql still work?

### ISSUE THREAD

**Issue by spyder-ian** [dbmail/dbmail#182]
I've build the docker container image and it connects to my database but immediately ends and says to try creating the tables.   The tables were created with the postgresql create tables script.   

How can I debug this?

**Comment by alan-hicks** [comment]
It sounds as though dbmail can't see the database tables.
Check the owner of the database tables:
Log in to Postgres using the dburi in dbmail.conf and check you have sufficient permissions.
Check the dbmail errorlog

**Comment by spyder-ian** [comment]
Thank you!   It was db perms for that user.   That and the auth_sql stuff.  Thank you!
