### ISSUE TITLE
Encountered with Debian 11

### ISSUE THREAD

**Issue by gomanuke** [dbmail/dbmail#184]
Hi, guys.
I stayed alone with dbmail working under Debian 10.13 from admin, who leaved a project some time ago.
And now I need host to go Debian 11. Not by upgrading, but by creating a new one with Debian 11 and repeating a mail configuration (exim spamassassin dbmail clamav). But I'm not so experienced to compile a project dbmail. It seems to be not so simple.

Please help me to figure out, does exist a simple way to do that? 
Or may be I should think to leave dbmail and go to file storing of mail.

Appreciate for any advices and comments.

**Comment by CozC** [comment]
Salve,

Alan has expertise in your suite of configurations and also he has  
published a number of documents describing your problem quite extensively.

Please visit dbmail.org.

Hope it helps.
-- 
CC @gmail

**Comment by alan-hicks** [comment]
Hello @gomanuke,

I've compiled and used dbmail under Ubuntu 22.04 so it should work with the latest Debian.

Thanks to recent sponsorship from XML Team upgrading gmime all libraries are up to date.

There is Debian specific documentation at https://github.com/dbmail/dbmail/tree/master/debian any feedback would be appreciated, let me know how you get on and I will add it to the dbmail website.

Please let me know if you have any issues.
Alan

**Comment by gomanuke** [comment]
Yes, i will, guys.  Thank You.
