### ISSUE TITLE
Service dbmail-imapd doesn't start

### ISSUE THREAD

**Issue by VladislavKara** [dbmail/dbmail#185]
OS: Ubuntu 20.04 and try CentOS 8 Stream

We installed all libraries and packages, install Database, service can connect to database and create user, but when i want to start service it shutdown with error timeout, what is it mean?
Logs are empty

Mar 06 10:06:56 {SERVER NAME} systemd[1]: Starting DBMail Imap Server...
Mar 06 10:08:26 {SERVER NAME} systemd[1]: dbmail-imapd.service: start operation timed out. Terminating.
Mar 06 10:08:26 {SERVER NAME} systemd[1]: dbmail-imapd.service: Failed with result 'timeout'.
Mar 06 10:08:26 {SERVER NAME} systemd[1]: Failed to start DBMail Imap Server.
Mar 06 10:08:29 {SERVER NAME} systemd[1]: dbmail-imapd.service: Scheduled restart job, restart counter is at 2.

**Comment by CozC** [comment]
Please check if
- dbmail.conf (/etc/dbmail.conf) is the one used in dbmail-imap.service
- check the dburl sting in properties in /etc/dbmail.conf) is the right  
one to access the database.
- check also (alter restarting) the service is binding the 143 port.  
(`netstat -tulpn`)

Hope it helps.
-- 
CC @gmail

**Comment by alan-hicks** [comment]
You probably want to raise the file_logging_levels to find the issue, the defaults are low for production.

Set the log level to the sum of the values next to the levels you want to record.
#   1 = Emergency 
#   2 = Alert
#   4 = Critical
#   8 = Error
#  16 = Warning
#  32 = Notice
#  64 = Info
# 128 = Debug
# 256 = Database -> Logs at debug level
# Examples:   0 = Nothing
#            31 = Emergency + Alert + Critical + Error + Warning
#           511 = Everything

https://github.com/dbmail/dbmail/blob/master/dbmail.conf

**Comment by VladislavKara** [comment]
Now configure:
- DBMail 3.3.1
- Postgresql 12
- CentOS 8

Thanks for your answers, I update my config and enable logs, but I don't understand why it is not working
I attach log file after start service and config

LOG dbmail.err:
[dbmail.log](https://github.com/dbmail/dbmail/files/10905907/dbmail.log)

My config:
[dbmail.txt](https://github.com/dbmail/dbmail/files/10905908/dbmail.txt)

**Comment by VladislavKara** [comment]
Okay, I understand, it's my problem, uncorrect build service, I forgot about --prefix=/usr when I ran build, I took params from sh scripts `--prefix=/usr --exec-prefix=/usr --sysconfdir=/etc --enable-systemd --with-logdir` and it work
Sorry for this and thank for help
