### ISSUE TITLE
dbmail 3.3.x fails to build under Ubuntu Server 22.04

### ISSUE THREAD

**Issue by ezplanet** [dbmail/dbmail#187]
I have an Ubuntu Server 22.04 instance where I build dbmail up to release 3.2.6.
I have just pulled the new code and dbmail fails to build.

Please see the build log below where it fails:

#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_LDAP_H 1
#define HAVE_LDAP_H 1
#define AUTHLDAP 1
#define HAVE_LDAP_INITIALIZE 1
#define SIEVE 1
#define HAVE_MATH_H 1
#define HAVE_MHASH_H 1
#define HAVE_EVENT_H 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_ZDB_H 1
#define HAVE_GETOPT_H 1
#define HAVE_GETOPT_LONG_ONLY 1
#define HAVE_DN_EXPAND 1

configure: exit 1
dh_auto_configure: error: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --sysconfdir=/etc/dbmail --localstatedir=/var/run/dbmail --with-logdir=/var/log/dbmail --enable-shared=yes--disable-static --with-ldap --with-sieve --enable-manpages --enable-systemd returned exit code 1
make[1]: *** [debian/rules:21: override_dh_auto_configure] Error 255
make[1]: Leaving directory '/home/mauro/dbmail/dbmail'
make: *** [debian/rules:18: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by alan-hicks** [comment]
Could you provide more information on what failed?
Perhaps turn up debugging.

There's a working example using Docker and Ubuntu jammy 22.04, perhaps that might offer some help

I'm not familiar with debian/rules:21: override_dh_auto_configure, perhaps there is something in there that the build doesn't like.

**Comment by alan-hicks** [comment]
Closing as there are working examples and insufficient feedback to diagnose this issue.
