### ISSUE TITLE
Emojis in the mail subject

### ISSUE THREAD

**Issue by PtY1968** [dbmail/dbmail#188]
The subjects aren't visible on mail list when they contains some type of emojis. When I select the mail, emoji shown in the preview pane's subject part, but not in the list.
I know, the subject fields there are in other table/view separated to full mail body, and the preview works with the full rfc822 content.
Other imap servers haven't problem with the listing subject what contains emojis.
Do you plan fix this problem?

**Comment by alan-hicks** [comment]
Closing as already fixed and no further feedback. Please reopen if this is still an issue.
