### ISSUE TITLE
Postgres config issues

### ISSUE THREAD

**Issue by tarkhil** [dbmail/dbmail#190]
1. Is dbmail ignoring max_db_connections? I've set it up to 30, but dbmail runs more while using only 15-20 at a time
2. Is it possible to disable prepared statements? I'd use pgbouncer, but it will fail on prepared messages

**Comment by alan-hicks** [comment]
dbmail pools connections per service, if you run multiple services imap, lmtp and sieve then it can use more.

libzdb is the database abstraction layer and prepared statements are integral to how dbmail interacts with the database. It's unlikely to be easy to untangle them.
https://www.tildeslash.com/libzdb/#api

**Comment by tarkhil** [comment]
1. Ok, I see now. But what does the message `May 21 21:30:05 mail dbmail/imap4d[35208]: Alert:[db] db_con_get(+321): Thread is having trouble obtaining a database connection. Try [0]` mean? Postgres is never near limit of connection
2. If pooling works ok, that's not a problem, thanks

**Comment by alan-hicks** [comment]
You may be experiencing issues with so many connections. Maybe lower max_db_connections as they're pooled, you rarely need more than the default (10). There are better ways to scale than increasing connections.

**Comment by tarkhil** [comment]
Okay, I'll see if 15 would perform better. Any more ideas to scale?

**Comment by alan-hicks** [comment]
It's usually better to have more smaller imap services than one large one.
Scaling is on my task list, alas I currently have little time to work on it.

**Comment by tarkhil** [comment]
Idea looks reasonable, but dbmail seems to ignore

```
NCHILDREN=2             # Default number of child processes to start.
MAXCHILDREN=10          # Maximum number of child processes allowed.
MINSPARECHILDREN=2      # Unused children to always have availale.
MAXSPARECHILDREN=4      # Maximum unused children allowed to be active.
```

either in DBMAIL or in IMAP sections.

**Comment by alan-hicks** [comment]
Yes, from UPDATING:
Starting with version 2.3.3 dbmail has switched to a single process that uses a event-driven architecture to handle many many concurrent clients. Where needed a pool of worker threads is used to process database transactions. Currently, only the IMAP server is multi-
threaded. Database transactions are handled by a single shared dynamic database connection pool to minimize the number of overall database connections.  

All this means that a number of configuration options are now redundant. You can remove the following items from dbmail.conf:

NCHILDREN
MAXCHILDREN
MINSPARECHILDREN
MAXSPARECHILDREN
MAXCONNECTS
