### ISSUE TITLE
Memory leaking?

### ISSUE THREAD

**Issue by tarkhil** [dbmail/dbmail#191]
Under a load, on 2000+ accounts with large mailboxes (about a terabyte database total) memory seems to grow, until dbmail-imap eats all available (around 40 Gb) memory and gets killed by OOM.

What's a normal dbmail-imap memory usage?

**Comment by alan-hicks** [comment]
Sadly memory leaks are a known issue. The majority are from libraries over which there is no control. Paul my predecessor and myself worked extensively to track and fix leaks in dbmail so most of them are gone. If you become aware of a set of imap commands that is repeatable I would be happy to investigate, but all the easy wins are fixed.

Everyone has different usage patterns so there are no current memory recommendations, feedback on what works best for you would be welcome.

One of my aims is to create a generic docker image that can be spun up and culled to reduce this impact.

**Comment by hemml** [comment]
I’m just starting multiple instances of dbmail daemon, using docker compose and a haproxy daemon (also under the docker) behind them. If the system killing one of the processes, most of working users are not affected. Just a workaround.  

The disadvantage of this configuration — imap daemons will see no source IP addresses of clients.

**Comment by CozC** [comment]
In a previous answer I have mentioned about an internal index of messages/folder that dbmail-imap does, so I believe is not about a memory leak is more to do with large mailboxes or number of mailboxes. You may try to shorten the timeout variable to make it short. In this case  if dbmail does  not receive any input from the user, it will deallocate memory reserved to the specified user which in turn have register to receive updates about message received.
