### ISSUE TITLE
Сould not load sort module

### ISSUE THREAD

**Issue by gomanuke** [dbmail/dbmail#205]
Hi.
Would You help me to figure out, what i misse with 3 3 1 (3 4 0) on Debian 11 ?

dbmail/lmtpd[9464]: EMERGENCY:[sort] sort_load_driver(+82): could not load sort module - turn up debug level for details

**Comment by alan-hicks** [comment]
Set file_logging_levels = 511 in dbmail.conf for everything.

Which version are you running 3.3.1 or 3.4.0?

**Comment by gomanuke** [comment]
It seems that problems was solved by **configure --with-sieve=/usr/local/lib/dbmail** while compiling, I'll check logs today and close issue if so.

**Comment by gomanuke** [comment]
Solved as it's said.

**Comment by alan-hicks** [comment]
DBMail doesn't have libsieve so /usr/local/lib/dbmail appears misleading.

The --with-sieve should be where your libsieve lives, it might be /usr/lib, on mine it's /usr/local/lib/libsieve.so YMMV

I would normally expect to see:
configure --with-sieve=/usr/local/lib
or
configure --with-sieve=/usr/lib
