### ISSUE TITLE
 Duplicate entry for key 'dbmail_header.PRIMARY' (BUG)

### ISSUE THREAD

**Issue by gomanuke** [dbmail/dbmail#206]
Hi!
Please would You advice me what should i do with errors like that (Debian 11 dbmail 3 4 0)

 dbmail/lmtpd[10819]: Error:[message] _header_insert(+1615): SQLException: Duplicate entry '50280-17-299421' for key 'dbmail_header.PRIMARY'

 dbmail/lmtpd[9464]: Error:[message] _header_insert(+1615): SQLException: Duplicate entry '50279-17-299437' for key 'dbmail_header.PRIMARY'

**Comment by alan-hicks** [comment]
If you turn up the debugging level file_logging_levels = 511 you should be able to track the error.

**Comment by gomanuke** [comment]
It seems to concerns #209 Investigating in progress...

**Comment by gomanuke** [comment]
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Debug:[message] _header_insert(+1603): Inserting header: [50363] [17] [299421]
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Database:[db] db_con_get(+330): [0x5594219f84a0] connection from pool
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Database:[db] db_con_clear(+365): [0x5594219f84a0] connection cleared
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Database:[db] db_begin_transaction(+642): BEGIN
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Database:[db] db_stmt_prepare(+493): [0x5594219f84a0] [INSERT INTO %sheader (physmessage_id, headername_id, headervalue_id) VALUES (
?,?,?)]
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Database:[db] db_stmt_set_u64(+513): [0x559421a40760] 1:[50363]
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Database:[db] db_stmt_set_u64(+513): [0x559421a40760] 2:[17]
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Database:[db] db_stmt_set_u64(+513): [0x559421a40760] 3:[299421]
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Error:[message] _header_insert(+1615): SQLException: Duplicate entry '50363-17-299421' for key 'dbmail_header.PRIMARY'
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Database:[db] db_rollback_transaction(+657): ROLLBACK
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Database:[db] db_con_close(+358): [0x5594219f84a0] connection to pool

I  checked 
_select * from dbmail_header where physmessage_id=50363 and headername_id=17 and headervalue_id=299421;_
It returns one row. In the same time i successfully get incoming mail...

**Comment by gomanuke** [comment]
On every incoming mail dbmail shots in log 

Aug 29 17:07:56 front dbmail/lmtpd[44605]: Error:[message] _header_insert(+1615): SQLException: Duplicate entry '50396-17-299421' for key 'dbmail_header.PRIMARY'

But 
_select * from dbmail_header where physmessage_id=50396 and headername_id=17 and headervalue_id=299421;_
returns 1 record and mail functionality itself seems to be ok...

**Comment by gomanuke** [comment]
Well. it look as dbmail tries to add a record twice...
Aug 29 17:19:52 front dbmail/lmtpd[65067]: Error:[message] _header_insert(+1615): SQLException: Duplicate entry '50397-17-299421' for key 'dbmail_header.PRIMARY'
![image](https://github.com/dbmail/dbmail/assets/47693546/f4123200-a2e7-43cc-92a1-2cf68f6fc2f2)

**Comment by gomanuke** [comment]
Here You are a **bug** (PRAMARY constraint deleted)

![image](https://github.com/dbmail/dbmail/assets/47693546/4cb022ba-54bc-4645-8a6f-386de813082e)

**Comment by alan-hicks** [comment]
That primary constraint is required, it's both the primary key and ensures redundant duplicate records are not inserted.

I'm currently unable to reproduce that error. Were there any warnings when you built dbmail 3.4?

**Comment by hemml** [comment]
I'm also have a lot of error like:

```
# grep 'duplicate key value violates unique constraint "dbmail_header_pkey"' dbmail.err | tail -n 3
Aug 29 17:41:46 b54372106d74 dbmail-lmtpd[11]: [0x5564e3150a70] Error:[message] _header_insert(+1621): SQLException: ERROR:  duplicate key value violates unique constraint "dbmail_header_pkey"
Aug 29 17:42:00 b54372106d74 dbmail-lmtpd[11]: [0x5564e3150a70] Error:[message] _header_insert(+1621): SQLException: ERROR:  duplicate key value violates unique constraint "dbmail_header_pkey"
Aug 29 17:42:13 b54372106d74 dbmail-lmtpd[11]: [0x5564e3150a70] Error:[message] _header_insert(+1621): SQLException: ERROR:  duplicate key value violates unique constraint "dbmail_header_pkey"
# grep 'duplicate key value violates unique constraint "dbmail_header_pkey"' dbmail.err | wc -l
382721
```

The error is not affects anything, but appears every time, when a message with multiple headers of same name is processing (like `Received:` headers, for example). I'm just ignoring them, but log is full of error this type.

**Comment by alan-hicks** [comment]
I can see how this could happen with duplicate header names. Do you have a sample of the headers names it's trying to duplicate? Also have you set header_cache_readonly? If not I suggest setting it and deleting any offending header names that aren't part of the core From, To, Reply-to, Cc, Bcc, Return-path, Subject, Date.

**Comment by hemml** [comment]
I have this section commented in `dbmail.conf`:

```
# header_cache tuning
#
# set header_cache_readonly to 'yes' to prevent new
# unknown header-names from being cached.
#
# header_cache_readonly = yes
```

Typically (and I have assumed it) that means the default value is "yes", but may be not in this case)
I will try to set it to "yes" while migrating to the new version.
Thanks!

**Comment by alan-hicks** [comment]
It isn't the default, though it should be. Thanks for highlighting this, it'll work on a fix.

**Comment by gomanuke** [comment]
Setting _header_cache_readonly = yes_ changed nothing for me. 
BTW header 17 (return-path) comes from message in two faces  return-path and **R**eturn-path
So here You are not unique case.

**Comment by gomanuke** [comment]
Anyway it is definitely a problem that i gues should be analyzed. 
Even **echo "BODY" | mail -s "TEST" root** shot that.

I'll try to get from exim a full message with headers that it sends to dbmail.

**Comment by gomanuke** [comment]
Here You are a log for **echo "BODY1" | mail -s "TEST1" root** command
[dbmail.err.zip](https://github.com/dbmail/dbmail/files/12496907/dbmail.err.zip)

**Comment by gomanuke** [comment]
Still in stuck...
Table dbmail_headername has PRIMARY key by id, so sql select * from dbmail_headername where id=17; returns one record.
Is this problem?
I attached export of my dbmail_headername 
[dbmail_headername.zip](https://github.com/dbmail/dbmail/files/12497732/dbmail_headername.zip)

**Comment by alan-hicks** [comment]
Your issue appears to be duplicate Return-Path entries in an email. I'm surprised you're getting those duplicate headers in the email as there would normally only be a single entry for return-path.

If you're getting multiple Return-Path headers in your emails I would investigate where they're coming from as your example suggests it's your system. RFC 5321 mentions Return-Path and there may be more than one: https://datatracker.ietf.org/doc/html/rfc5321

The dbmail_headername table has headers that are cached in dbmail_header.

If you delete the entry in dbmail_headername then they won't get inserted into dbmail_header and you won't get the error. Unless you need those headers cached, then deleting them will improve performance as they won't get added.

**Comment by gomanuke** [comment]
Appreciate for Your patient explanation. 
Deleting headers from dbmail's scope (when incoming email message consists it) is not so good idea from my modest opinion.
I use exim as MTA, so i'll try to investigate id Eximm add extra return-path.

**Comment by alan-hicks** [comment]
Making dbmail efficient has also made it complicated.

An email is identified in dbmail_messages as to who owns it and in what folder it is stored, that email is divided into parts and they are stored in dbmail_mimeparts with dbmail_partlists understanding how those parts fit together. Because it's highly efficient there is a need to extract some parts of the email such as subject, from and date. These headers are extracted from the email and cached in dbmail_header, dbmail_headername and dbmail_headervalue.

DBMail only uses some headers and doesn't need return-path. From a dbmail perspective not caching the Return-Path header by removing or not including that entry from dbmail_headername is more efficient.

Caching custom headers may be useful, but as Return-Path like Received headers are not unique, unless you're just testing for their existence, you would need to inspect the original header in dbmail_mimeparts to obtain multiple values.

I hope this clarifies the structure and purpose of a few of the dbmail tables.

**Comment by alan-hicks** [comment]
Your example echo "BODY1" | mail -s "TEST1" showed the duplicate return-path in error log. This strongly suggests those headers are added by the MTA.
