### ISSUE TITLE
Is branch main correct and stable

### ISSUE THREAD

**Issue by gomanuke** [dbmail/dbmail#207]
So it looks as i got working configuration with dbmal 3.4 on Debian 11 !!!

I'de like to have updated version of dbmail by _git merge - configure - make - make install_
So would You clarify is branch **main** (what i got after _git clone_) correct and suitable for production?

**Comment by alan-hicks** [comment]
Congratulations on getting dbmail working on Debian 11.

Yes, branch main is the project default and tag v3.4.0 is suitable for production. Branch 3.4.0 will be used for bugfixes as they arise. Branch main is used for all development, may have new or changed functionality, may not have been widely tested, and may not be suitable for production.
