### ISSUE TITLE
"Double" error logging of dbmail (miracle)

### ISSUE THREAD

**Issue by gomanuke** [dbmail/dbmail#209]
As i said erlier i've just got working dbmail 3 4 0 on Debian 11. So my system is full of "miracles" ))).

Here You are, guys my dbmail.conf log's setting _errorlog  = /var/log/dbmail.err_
But at Aug 27 19:51 **something** creates empty dbmail.err in /var/log/dbmail/ (existing dir, creates just the file) and writes into /var/log/mail.err, /var/log/mail.warn, /var/log/mail.log:

```
Aug 27 19:51:18 front dbmail/maintenance[2584]: Error:[db] db_query(+437): SQLException: no such table: dbmail_users
Aug 27 19:51:18 front dbmail/maintenance[2584]: Error:[db] db_query(+438): failed query [SELECT 1=1 FROM dbmail_users LIMIT 1 OFFSET 0]
Aug 27 19:51:19 front dbmail/maintenance[2584]: Error:[db] check_upgrade_step(+964): SQLException: no such table: dbmail_upgrade_steps
```
Would You help me to figure out, what's happening?

**Comment by alan-hicks** [comment]
Please check your dbmail.conf as the database can't find the tables dbmail_user and dbmail_upgrade_steps.

SQLException: no such table: dbmail_user
SQLException: no such table: dbmail_upgrade_steps

**Comment by gomanuke** [comment]
That tables are ok attached) as dbmail itself. Everything is working: from authetfication to mail sending and receving. 
It looks, as some "second dbmail" with other conf trying to use default dbmail.conf from local git directory.
It is original dbmail.conf that contains errorlog = /var/log/**dbmail**/dbmail.err
My conf contains errorlog = /var/log/dbmail.err

![image](https://github.com/dbmail/dbmail/assets/47693546/a961f39c-6bd6-45c8-a4d0-35ebd52c17ef)

**Comment by alan-hicks** [comment]
Perhaps you have two dbmail instances running. The error suggests the configuration file it's using doesn't have your dburi.

You can check  with: ps -ax | grep dbmail

**Comment by gomanuke** [comment]
Sorry...
`grep dbmail
  26325 ?        Sl     0:00 /usr/local/sbin/dbmail-imapd -f /etc/dbmail/dbmail.conf
  26342 ?        Sl     0:00 /usr/local/sbin/dbmail-pop3d -f /etc/dbmail/dbmail.conf
  26351 ?        Sl     0:00 /usr/local/sbin/dbmail-lmtpd -f /etc/dbmail/dbmail.conf
  26363 ?        Sl     0:00 /usr/local/sbin/dbmail-timsieved -f /etc/dbmail/dbmail.conf
`
I'll try to get original dbmail.conf...
