### ISSUE TITLE
dbmail.err contains references on dbmail/src/modules/

### ISSUE THREAD

**Issue by gomanuke** [dbmail/dbmail#210]
Hi!
Would You clarify the situation with cat /var/log/dbmail/dbmail.err | grep root/ that returns 
Aug 28 19:30:34 front dbmail-imapd[34834]: [0x7f8cc262ae00] Debug:[auth] auth_load_driver(+72): looking for auth_sql as /root/dbmail/src/modules/.libs/libauth_sql.so
Aug 28 19:30:34 front dbmail-pop3d[34851]: [0x55a8a7594000] Debug:[auth] auth_load_driver(+72): looking for auth_sql as /root/dbmail/src/modules/.libs/libauth_sql.so
Aug 28 19:30:34 front dbmail-lmtpd[34860]: [0x5594219ca000] Debug:[auth] auth_load_driver(+72): looking for auth_sql as /root/dbmail/src/modules/.libs/libauth_sql.so
Aug 28 19:30:34 front dbmail-timsieved[34870]: [0x55f450871000] Debug:[sort] sort_load_driver(+70): looking for sort_sieve as /root/dbmail/src/modules/.libs/libsort_sieve.so
Aug 28 19:30:34 front dbmail-timsieved[34872]: [0x55f450871000] Debug:[auth] auth_load_driver(+72): looking for auth_sql as /root/dbmail/src/modules/.libs/libauth_sql.so
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Debug:[sort] sort_load_driver(+70): looking for sort_sieve as /root/dbmail/src/modules/.libs/libsort_sieve.so
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Info:[sort] sort_load_driver(+74): cannot load /root/dbmail/src/modules/.libs/libsort_sieve.so: cannot open shared object file: Permission denied

I did nothing except 
./configure --with-sieve=/usr/local/lib/dbmail
make
systemctl stop dbmail
make install
systemctl start dbmail

**Comment by gomanuke** [comment]
Here You are a lib searching...
cat /var/log/dbmail/dbmail.err | grep libsort_sieve.so

Aug 28 19:30:34 front dbmail-timsieved[34870]: [0x55f450871000] Debug:[sort] sort_load_driver(+70): looking for sort_sieve as /root/dbmail/src/modules/.libs/libsort_sieve.so
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Debug:[sort] sort_load_driver(+70): looking for sort_sieve as /root/dbmail/src/modules/.libs/libsort_sieve.so
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Info:[sort] sort_load_driver(+74): cannot load /root/dbmail/src/modules/.libs/libsort_sieve.so: cannot open shared object file: Permission denied
Aug 28 19:35:17 front dbmail-lmtpd[34860]: [0x5594219ca000] Debug:[sort] sort_load_driver(+70): looking for sort_sieve as /usr/local/lib/dbmail/libsort_sieve.so

**Comment by gomanuke** [comment]
root@front:~/dbmail# git branch
* 3.4.x
  main

root@front:~/dbmail# git merge 3.4.x
Already up to date.

And here You are configure that i run as configure --with-sieve=/usr/local/lib/dbmail

But dbmail.err still contains 

Aug 28 21:21:02 front dbmail-imapd[44248]: [0x7f5e9082ae00] Debug:[auth] auth_load_driver(+72): looking for auth_sql as /root/dbmail/src/modules/.libs/libauth_sql.so
Aug 28 21:21:02 front dbmail-pop3d[44265]: [0x556e42441000] Debug:[auth] auth_load_driver(+72): looking for auth_sql as /root/dbmail/src/modules/.libs/libauth_sql.so
Aug 28 21:21:02 front dbmail-lmtpd[44274]: [0x556573b49000] Debug:[auth] auth_load_driver(+72): looking for auth_sql as /root/dbmail/src/modules/.libs/libauth_sql.so
Aug 28 21:21:02 front dbmail-timsieved[44284]: [0x5651adf3f000] Debug:[sort] sort_load_driver(+70): looking for sort_sieve as /root/dbmail/src/modules/.libs/libsort_sieve.so
Aug 28 21:21:02 front dbmail-timsieved[44286]: [0x5651adf3f000] Debug:[auth] auth_load_driver(+72): looking for auth_sql as /root/dbmail/src/modules/.libs/libauth_sql.so



[configure.zip](https://github.com/dbmail/dbmail/files/12456492/configure.zip)

**Comment by alan-hicks** [comment]
Oops my bad, the --with-sieve should be where your libsieve lives, on mine it's /usr/local/lib/libsieve.so YMMV

configure --with-sieve=/usr/local/lib

**Comment by alan-hicks** [comment]
You need to install dbmail rather than run it from your build directory.

**Comment by gomanuke** [comment]
But make install made that job, right? Here You are a proof

systemctl status dbmail
● dbmail.service - LSB: Start dbmail services
     Loaded: loaded (/etc/init.d/dbmail; generated)
     Active: active (running) since Tue 2023-08-29 17:34:23 +05; 54min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 65931 ExecStart=/etc/init.d/dbmail start (code=exited, status=0/SUCCESS)
      Tasks: 18 (limit: 154368)
     Memory: 15.9M
        CPU: 607ms
     CGroup: /system.slice/dbmail.service
             ├─65939 /usr/local/sbin/dbmail-imapd -f /etc/dbmail/dbmail.conf
             ├─65956 /usr/local/sbin/dbmail-pop3d -f /etc/dbmail/dbmail.conf
             ├─65965 /usr/local/sbin/dbmail-lmtpd -f /etc/dbmail/dbmail.conf
             └─65977 /usr/local/sbin/dbmail-timsieved -f /etc/dbmail/dbmail.conf

Aug 29 17:34:23 front systemd[1]: Starting LSB: Start dbmail services...
Aug 29 17:34:23 front dbmail[65931]: Starting dbmail servers: dbmail-imapd dbmail-pop3d dbmail-lmtpd dbmail-timsieved.
Aug 29 17:34:23 front systemd[1]: Started LSB: Start dbmail services.

**Comment by alan-hicks** [comment]
Those debug traces are just informational for tracking module load errors.
Debug:[auth] auth_load_driver(+72): looking for auth_sql as /root/dbmail/src/modules/.libs/libauth_sql.so

It's part of the for loop (68-79) https://github.com/dbmail/dbmail/blob/main/src/authmodule.c

If the module couldn't be found it would error out with "could not load auth module - turn up debug level for details"
