### ISSUE TITLE
Turning on certificates on TLS (993) breaks IMAP authentification on port 143

### ISSUE THREAD

**Issue by gomanuke** [dbmail/dbmail#215]
Hi guys.

As i said 3.4.0 successfully works on my production but with **crutch** (stunnel). 
I use "local" web-client RoundCube (auth via port 143) and "remote" mobile android clients (auth via port 993).
If TLS and certificates turned on dbmail (tls_cafile, tls_cert, tls_key, tls_port=993), then 143 breaks for local client (mobile remains ok) So i need to install stunnel with:

[imaps]
accept  = 993
connect = 127.0.0.1:143
cert = /etc/stunnel/my-site-cert.pem

It leads to dbmail listening **just** 143 but accessible also through 993 certificates (stunnel).
Would You help me to figure out what is the problem with accessing via 143 when 993 certificates is on?

**Comment by alan-hicks** [comment]
What issue are you having?

Does dbmail-imapd on port 443 offer STARTTLS?

The three required tls entries in dbmail.conf are: tls_cafile, tls_cert and tls_key, tls_ciphers is optional.

Is tls_port commented out? If so uncomment it and port 993 should become available.

**Comment by CozC** [comment]
Salve,An alternative solution, and also a little bit safe is to use haproxy on same machine, bind with 993 which fallbacks to 143 locally(or install 2 instances of dbmail to prevent unexpected shutdown of dbmail-imap, sometimes it happens)Haproxy(tcp proxy) has better performance on ssl and leaves alone dbmail-imap to do his job without having to deal with ssl traffic. In case the machine that deals with imap has other services installed (eg httpd) you can use the same approach (make it front end for service, in my example http proxy). Another reason is that helps if you want to monitor the connection load(ex zabbix, nagios, etc), you end up having just one place to check, not all services which may have such a facility or not and integration might be little bit a small nightmare. Hope it helps.CC @ gmail
-------- Original message --------From: Alan Hicks ***@***.***> Date: 8/30/23  13:19  (GMT+02:00) To: dbmail/dbmail ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [dbmail/dbmail] Turning on certificates on TLS (993) breaks IMAP authentification on port 143 (Issue #215) 
What issue are you having?
Does dbmail-imapd on port 443 offer STARTTLS?
The three required tls entries in dbmail.conf are: tls_cafile, tls_cert and tls_key, tls_ciphers is optional.
Is tls_port commented out? If so uncomment it and port 993 should become available.
