### ISSUE TITLE
SQL of creating new user and its mailboxes

### ISSUE THREAD

**Issue by gomanuke** [dbmail/dbmail#229]
Hi guys.
I'd like to clarify steps to create user via SQL queries. 
What does that flag means? And what values i should use while creating it for new just inserted user?

I've seen advices as 
INSERT INTO dbmail_mailboxes 
       (owner_idnr, name, seen_flag, answered_flag, deleted_flag, flagged_flag, recent_flag, draft_flag, permission)
       VALUES (<the_retrieved_public_useridnumber>, 'Inbox', 1, 1, 1, 1, 1, 1, 2 );

in the same time RoundCube with option auto_create_folders uses:

INSERT INTO dbmail_mailboxes 
       (owner_idnr, name, seen_flag, answered_flag, deleted_flag, flagged_flag, recent_flag, draft_flag, permission)
       VALUES (<the_retrieved_public_useridnumber>, 'Inbox', 0, 0, 0, 0, 0, 0, 2 );

**Comment by alan-hicks** [comment]
Hi Sasha,

Adding users via sql isn't recommended, you can find links to all the code from db_user.c it creates a user, mailbox and alias.

The query you're probably looking for is:

    INSERT INTO dbmail_mailboxes (name, owner_idnr, permission, seq) VALUES ('Inbox', owner_idnr, 2, 1)

Permission (2) is Read/Write and the sequence for a new folder starts with 1.

Hope this helps,
Alan

**Comment by gomanuke** [comment]
Thanks, for advices, Alan.
What You'd can prefer instead of SQL? 
Ans my task is synchronizing dbmail's users with master-system, containing cloud users. 
I don't understand what i shoud use...

**Comment by alan-hicks** [comment]
Nothing wrong with using sql, and if you're synchronising users from a sql database then that may be your best option. Be careful of updating those tables though, imap updates them when accessing and delivering emails. Also there will probably be a schema change soon.

Using the command line dbmail-users will always be supported so it's the recommended way to update users.

**Comment by gomanuke** [comment]
In fact i just need to
- insert dbmail_users
- insert dbmail_mailboxes
- insert sbmail_aliases

But DB structure for me is mysterious thing. May i hope to get some docs about it here?
And one more thing concerning dbmail-users. It's strange, but dbmail-users -a username -w pswd makes nothing in database's tables... But reports about success. As dbmail-users -s username returns nothing...

**Comment by alan-hicks** [comment]
I'm currently working on docs for the schema but it's not ready yet, sorry.

Try turning up debug levels to find out what's happening.

If authdriver is set to ldap dbmail will try to add the user to the ldap directory.

**Comment by gomanuke** [comment]
> I'm currently working on docs for the schema but it's not ready yet, sorry.
Alan, I do appreciate You for Your really great work!
Would just verify me sql, that add new user. Is this correct values? It's really stauck for me to analyze C-sources (((
I aware about flags... Here You are:

```
INSERT INTO mail_db.dbmail_users (userid, passwd, client_idnr, maxmail_size, encryption_type, last_login) 
VALUES ('p_login', 'p_password', 0 , 0, '', CURRENT_TIMESTAMP);

select LAST_INSERT_ID() into @p_user_id;

INSERT INTO mail_db.dbmail_mailboxes (name, owner_idnr,seen_flag, answered_flag, deleted_flag, flagged_flag, recent_flag, draft_flag, permission) 
VALUES ('INBOX', " . $p_user_id. ", 1, 1, 1, 1, 1, 1, 2);

INSERT INTO dbmail_aliases (alias, deliver_to) VALUES ('p_login@domain.com', $p_user_id);
```

**Comment by alan-hicks** [comment]
No need to include last_login when creating users, that's set when they login. Also if you set a last_login you can't tell if a user has never logged in.

No need to set flags when creating mailboxes.

Sequence isn't random, it's used for RFC 1762 https://datatracker.ietf.org/doc/html/rfc7162

**Comment by gomanuke** [comment]
Almost clear! ))
Would You clarify flags of mailboxes?
I mean **seen_flag, answered_flag, deleted_flag, flagged_flag, recent_flag, draft_flag**
Should I update it on existing INBOX (where it was set to 1)?

**Comment by alan-hicks** [comment]
You shouldn't update any flags unless you have a good reason to do so. They're used by IMAP and set when messages arrive.
