### ISSUE TITLE
Message's way to folder "Sent"

### ISSUE THREAD

**Issue by gomanuke** [dbmail/dbmail#230]
Hi, guys.
Please forgive me for that topic. It conserns not only dbmail. I need to get undestanding about MUA behaviour.
Appreciate for answers in advance. Here You are a scheme of dbmail existence.
Is this right opinion, that message that was sent from MUA to MTA (using as always port 25) can me placed into Sent folder just if MUA uses IMAP?
If exists a way from MTA (Exim) via dbmail-lmtpd (or dbmail-smtp)?
![image](https://github.com/dbmail/dbmail/assets/47693546/d7dbad57-87d4-4126-9a6e-c7d62403f602)

**Comment by alan-hicks** [comment]
When an email is sent from an MUA to an MTA, there are two things that happen.

The email is sent to the MTA via SMTP for onward submission.
The email is stored via IMAP in the users sent folder.

When an email is received by an MTA such as exim, it sends the email via lmtp or dbmail-deliver and unless there is a sieve script it will go to the user's inbox.

Hope this helps.

**Comment by gomanuke** [comment]
Alan, look, u have two mail clients:
1. RoundCube web0client that has as smtp and imap connection string (25 and 143 ports correspondently)
2. smtp client just with 25 port connection 

When 1 sends a message then it successfully got by receiver remains in Sent folder
When 2 sends a message then it successfully got by receiver  and NOT remains in Sent folder.
And of course incoming mail got by MTA go to dbmail...

So my sad conclusion is that MTA doesn't report  OUT mail to dbmail... 
Should I find a solution somewhere in MTA configuraton?

**Comment by alan-hicks** [comment]
Nothing to do with the MTA.

The sent folder is configurable for each mua, and they all have different defaults.

**Comment by gomanuke** [comment]
> When an email is received by an MTA such as exim, it sends the email via lmtp or dbmail-deliver and unless there is a sieve script it will go to the user's inbox.

My apologize, but thought, that MTA after receiving outcoming message from MUA (via 25-smtp) must report it to dbmail-lmtp as it does for every incoming messages...

**Comment by alan-hicks** [comment]
One of the wonders of imap - imapsync works by getting an email from one account and putting it into another:
https://imapsync.lamiral.info/
https://github.com/imapsync/imapsync
