### ISSUE TITLE
UTF-8 subjects not showing up

### ISSUE THREAD

**Issue by spliff1** [dbmail/dbmail#256]
Subjects are not visible for some mails encoded in UTF-8. Basically, this:
```
Subject: =?UTF-8?Q?=F0=9F=99=8C_Ai_confirmat_ordinul_de_?=
 =?UTF-8?Q?livrare!_Vezi_num=C4=83rul_AWB_=F0=9F=91=89?=
```

Results in this:
![Screenshot 2023-12-06 at 12 01 34](https://github.com/dbmail/dbmail/assets/87647667/29d3b3cf-78cc-4202-bb55-d4deed6cdc37)

I have multiple messages with this issue, and I can provide the whole message source in private if it helps to debug this. Also, this happens on both Roundcube and mobile mail clients, which makes me believe that it's IMAP related.

**Comment by alan-hicks** [comment]
If you're using mysql then applying upgrade.mysql should fix your issue.
It's related to mysql defaulting to utf8mb3 whereas utf-8 characters 🙌  👉 require utf8mb4

https://github.com/dbmail/dbmail/blob/main/sql/mysql/upgrades/upgrade.mysql

**Comment by spliff1** [comment]
Thank you! that fixed the issue, but only for the new mails. Is there anything I can do for the existing ones ?

**Comment by alan-hicks** [comment]
Perhaps dbmail-util -b might help (untested) it's a body/header/envelope cache check and may fix missing subjects.

**Comment by CozC** [comment]
Salve,

Can you share the header section where subject is encoded (print screen is  
ok).

When this happens usually there something along the following:
- client font cannot display the special chars in the subject (sometimes  
happens), my client displays a small rectangle in this situations.
- spaces (missing, this is a multi line header) or CR/LF wrongly added  
(from the example is impossible to tell if it is the case).

The encoding is correct according to RFC and also can be correctly   
decoded (so no issues there) .

Have a nice day

-- 
CC @gmail

**Comment by spliff1** [comment]
After running the query, deleting every result and running `dbmail-util -ay`, the subject was fixed for every existing mail. Thank you so much for the help!
