### ISSUE TITLE
systemd services stuck at "dispatching event loop"

### ISSUE THREAD

**Issue by tacerus** [dbmail/dbmail#271]
Hi,

I am packaging this for openSUSE and am building with `--enable-systemd`, which installs the respective service unit files using the `notify` mode (which is great to see out of the box!).

Unfortunately I cannot get the services to finish starting, they are stuck at "activating":

```
# systemctl status dbmail-imapd
● dbmail-imapd.service - DBMail Imap Server
     Loaded: loaded (/usr/lib/systemd/system/dbmail-imapd.service; disabled; vendor preset: disabled)
     Active: activating (start) since Thu 2024-04-11 22:57:45 CEST; 7s ago
   Main PID: 8456 (dbmail-imapd)
      Tasks: 12 (limit: 4915)
     CGroup: /system.slice/dbmail-imapd.service
             └─ 8456 /usr/sbin/dbmail-imapd -D

Apr 11 22:57:45 phoebe systemd[1]: Starting DBMail Imap Server...
```

With logging level 128 enabled:

```
...
Apr 11 22:56:54 phoebe dbmail/imap4d[8301]: Debug:[auth] auth_load_driver(+40): using default auth_sql
Apr 11 22:56:54 phoebe dbmail/imap4d[8301]: Debug:[auth] auth_load_driver(+47): no value for library_directory, using default [/usr/lib64/dbmail]
Apr 11 22:56:54 phoebe dbmail/imap4d[8301]: Debug:[auth] auth_load_driver(+72): looking for auth_sql as /home/abuild/rpmbuild/BUILD/dbmail-3.4.1/src/modules/.libs/libauth_sql.so
Apr 11 22:56:54 phoebe dbmail/imap4d[8301]: Debug:[auth] auth_load_driver(+76): cannot load /home/abuild/rpmbuild/BUILD/dbmail-3.4.1/src/modules/.libs/libauth_sql.so: cannot open shared object file: No such file or directory
Apr 11 22:56:54 phoebe dbmail/imap4d[8301]: Debug:[auth] auth_load_driver(+72): looking for auth_sql as /usr/lib64/dbmail/libauth_sql.so
Apr 11 22:56:54 phoebe dbmail/imap4d[8301]: Debug:[server] dm_bind_and_listen(+404): creating plain socket [9] on [0.0.0.0:143]
Apr 11 22:56:54 phoebe dbmail/imap4d[8301]: Debug:[server] server_run(+830): Adding event for plain socket [9] [1/1]
Apr 11 22:56:54 phoebe dbmail/imap4d[8301]: Debug:[server] server_run(+830): Adding event for plain socket [9] [1/1]
Apr 11 22:56:54 phoebe dbmail/imap4d[8301]: Debug:[server] server_run(+856): dispatching event loop...
Apr 11 22:57:42 phoebe systemd[1]: dbmail-imapd.service: Deactivated successfully.
Apr 11 22:57:42 phoebe systemd[1]: Stopped DBMail Imap Server.
Apr 11 22:57:45 phoebe systemd[1]: Starting DBMail Imap Server...
Apr 11 22:59:15 phoebe systemd[1]: dbmail-imapd.service: start operation timed out. Terminating.
Apr 11 22:59:15 phoebe systemd[1]: dbmail-imapd.service: Failed with result 'timeout'.
Apr 11 22:59:15 phoebe systemd[1]: Failed to start DBMail Imap Server.
```

The process itself however does seems to get started - the initial SQLite database file is created, and the `dbmail-imapd` process is listening on port 143. It is also remaining after the systemd service times out and accepts connections:

```
$ telnet localhost 143
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
* OK [CAPABILITY IMAP4rev1 AUTH=LOGIN AUTH=CRAM-MD5 ID LITERAL+] dbmail 3.4.1 ready.
```

Hence I assume some issue with passing the systemd notifications?

I used `dbmail-imapd` in the example above, but the behavior and last log line is the same with other services, such as `dbmail-lmtpd`.

This is with systemd 249 and dbmail 3.4.1.

Would appreciate any advice!
Georg

**Comment by alan-hicks** [comment]
The log line dispatching event loop... confirms it's started. Alas the systemd code hasn't been updated so it might take a while to discover what has changed.
I've a few urgent commitments so will get to this early next week.

**Comment by tacerus** [comment]
Thanks for confirming!

Upon closer inspection, I found the issue. It was not evaluating the HAVE_SYSTEMD ifdefs at all in my environment.

At build time, the configure script prints 

```
[   15s] checking for SYSTEMD... no
[   15s] checking for SYSTEMD... no
[   15s] checking for SYSTEMD... yes
```

but in config.log it returned no linker flags for it:

```
...
 OPENSSL:                   -lssl -lcrypto
 SYSTEMD:
 ZDB:                       -lzdb
...
```

It turned out, libsystemd was not available at build time. After resolving that, it does link correctly:

```
...
 SYSTEMD:                   -lsystemd
...
```

And sure enough, the services activate correctly now.

So I think my issue here can be considered invalid, however do you think it is a bug that the configure script does not abort and fail (exit > 0) if it cannot find libsystemd albeit `--enable-systemd` having been passed?

**Comment by alan-hicks** [comment]
The configure script uses pkg-config to check if systemd exists and what flags should be used.
Not sure aborting is good practice as config scripts are generated from automake.

**Comment by tacerus** [comment]
I understand, I'm not sure what a better approach would be, but it feels a bit "hidden" in config.log - especially when building in an automated environment a succeeding build suggests that all explicitly enabled components linked correctly.
