### ISSUE TITLE
problem with headers Thunderbird

### ISSUE THREAD

**Issue by kka22** [dbmail/dbmail#272]
Hello!
testing dbmail
We encountered a problem with displaying headers; they are in the body of the message, but they are not displayed in the Inbox, Outbox and other folders.
The problem is in both the BSD installation and docker

![error_headers](https://github.com/dbmail/dbmail/assets/111370247/c7bb5384-97dd-455d-8f9e-9b2ba7f53b52)

**Comment by alan-hicks** [comment]
Do you have the headers cached?

select count(*)
from dbmail_headername;

select *
from dbmail_headername
where headername = 'subject';

If not then set:
[DBMAIL]
header_cache_readonly = no

Deliver a few emails to populate the dbmail_headername table then reset caching:
[DBMAIL]
header_cache_readonly = yes

**Comment by kka22** [comment]
thanks It works!)
