### ISSUE TITLE
dbmail generates a possibly invalid BODYSTRUCTURE, that java clients don't like part 2

### ISSUE THREAD

**Issue by awheeler** [dbmail/dbmail#36]
New issue referenced in #23 , it looks like when a mulit-part email contains a part that is `message` type, sometimes java clients that use javax.mail blow up with this:
```
javax.mail.MessagingException: Unable to load BODYSTRUCTURE
        at com.sun.mail.imap.IMAPMessage.loadBODYSTRUCTURE(IMAPMessage.java:1564)
        at com.sun.mail.imap.IMAPMessage.getContentType(IMAPMessage.java:599)
        at msgshow.dumpPart(msgshow.java:258)
        at msgshow.main(msgshow.java:224)
```
In looking into the dbmail code, all parts of type `message` include envelope structure, body structure, and lines.
However, the RFC says:

> A body type of type MESSAGE and subtype RFC822 contains,
         immediately after the basic fields, the envelope structure,
         body structure, and size in text lines of the encapsulated
         message.

The java code that looks at this is [here](https://github.com/javaee/javamail/blob/829f1a035183af709b53c632d57edb1184c4a311/mail/src/main/java/com/sun/mail/imap/protocol/BODYSTRUCTURE.java#L297)

When I remove those 3 fields, the java library is happy, so I think we need to add a subtype check and only when the subtype is `rfc822`, include those 3 fields.

The samples I'm looking at:
From dbmail:
```
* 1 FETCH (BODYSTRUCTURE (("message" "delivery-status" ("charset" "UTF-8" "")  NIL NIL "8bit" 412 NIL NIL 14 "24589f11f73bab91c9b1223af056e777" ("attachment" NIL) "en-US" NIL)))
```
After removing the 3 rfc822 parts:
```
* 1 FETCH (BODYSTRUCTURE (("message" "delivery-status" ("charset" "UTF-8" "")  NIL NIL "8bit" 412 "24589f11f73bab91c9b1223af056e777" ("attachment" NIL) "en-US" NIL)))
```

The calling  code in dbmail is [here](https://github.com/dbmail/dbmail/blob/master/src/dm_misc.c#L1921) and [here](https://github.com/dbmail/dbmail/blob/master/src/dm_misc.c#L1575) and the implementation is [here](https://github.com/dbmail/dbmail/blob/master/src/dm_misc.c#L1692).

I do see the dbmail is explicitly checking in function **imap_get_logical_part** [here](https://github.com/dbmail/dbmail/blob/master/src/dm_misc.c#L2089) for message/rfc822, but not in **_structure_part_message**

**Comment by awheeler** [comment]
[Here](https://github.com/awheeler/dbmail/commit/09cb1dedff72adbc1d388a335f9fdc8d30600dd9) are the changes I'm looking at.
Lmk if that looks good or if you want me to add a trace.
Also, would you like the pull request against master?

**Comment by CozC** [comment]
The change looks straightforward, nice work.
A trace should be added and some comments regarding the "why".
After setting up traces, can you provide log trace by setting 511  
(file_logging_levels, syslog_logging_levels) for that specific case? (to  
better check the rfc specs.
Also, it would be nice if you can build a test program with this java lib  
to be run from CLI in order to investigate this client issues (it will  
invalidate the previous statement). I'm asking this test program in order  
to have a continuation and further investigate this client due to the fact  
that is very strict (or rigid), maybe incorporating it int test-scripts  
section.

Thank you .


On Tue, 07 Apr 2020 00:44:32 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> Here are the changes I'm looking at.
> Lmk if that looks good or if you want me to add a trace.
> Also, would you like the pull request against master?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by awheeler** [comment]
Yeah, that's a good idea.  I haven't dug into the testing part of dbmail yet, but I've built a test program using the java code, and that was super helpful.

Looking in the test-scripts folder, is that where you'd like the java code?  That would introduce a lot of new complexity, or do you just want some java, but leave it to users to do compilation and testing with it?

**Comment by awheeler** [comment]
This is what I'm thinking for the trace:
 ```
       /* body lines */
        if (g_mime_content_type_is_type(type,"message","rfc822")) {
                TRACE(TRACE_DEBUG, "Only send out envelope structure, body structure, and lines for subtype rfc822");
                /* envelope structure */
                b = imap_get_envelope(g_mime_message_part_get_message(GMIME_MESSAGE_PART(part)));
```

**Comment by CozC** [comment]
Salve,

The folder is indeed that, 'test-scripts'.
I'm in agreement with you, in terms of java code, I was thinking it will  
be best to add only the code per say (maybe joined into one file, or a  
folder named java-client (just a thought)) + a readme explaining how to  
build/run that specific tests.

--
Cosmin Cioranu

**Comment by CozC** [comment]
Perfect.
Do you think it will be beneficial to add some trace over the else branch?


On Tue, 07 Apr 2020 21:02:12 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> This is what I'm thinking for the trace:
>      /* body lines */
>       if (g_mime_content_type_is_type(type,"message","rfc822")) {
>               TRACE(TRACE_DEBUG, "Only send out envelope structure, body  
> structure, and lines for subtype rfc822");
>               /* envelope structure */
>               b =  
> imap_get_envelope(g_mime_message_part_get_message(GMIME_MESSAGE_PART(part)));
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by awheeler** [comment]
I was wondering the same ... would it be better to only put the trace on the else?
```
        if (g_mime_content_type_is_type(type,"message","rfc822")) {
                /* envelope structure */
                ...
        } else {
                TRACE(TRACE_DEBUG, "Subtype is not rfc822: excluding envelope structure, body structure, and lines as per RFC3501");
        }
```

**Comment by awheeler** [comment]
The code that I have is CLI code that I point at an IMAP repo, give it a login, and folder, and it will go through all the messages in the folder, erring out if there are any problems.

**Comment by CozC** [comment]
I see your point there is not point to trace the obvious, I'm in agreement  
with you.

On Tue, 07 Apr 2020 23:35:19 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> I was wondering the same ... would it be better to only put the trace on  
> the else?
>        if (g_mime_content_type_is_type(type,"message","rfc822")) {
>                /* envelope structure */
>                ...
>        } else {
>                TRACE(TRACE_DEBUG, "Subtype is not rfc822: excluding  
> envelope structure, body structure, and lines as per RFC3501");
>        }
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Perfect.
CLI code works for me, If you are willing to put it there it should be  
very valuable.

On Tue, 07 Apr 2020 23:39:45 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> The code that I have is CLI code that I point at an IMAP repo, give it a  
> login, and folder, and it will go through all the messages in the  
> folder, erring out if >there are any problems.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by awheeler** [comment]
Ok, cool.  i'll just add a comment instead of a trace then, and I'm working on the cli, which is just a stripped down version of sample code that came with the java library.

**Comment by CozC** [comment]
Ok.
Thank you.

On Wed, 08 Apr 2020 00:33:54 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> Ok, cool. i'll just add a comment instead of a trace then, and I'm  
> working on the cli, which is just a stripped down version of sample code  
> that came >with the java library.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by awheeler** [comment]
I've run into something very strange now, when running the java program against dbmail-imapd, where it's the only client, the java client will hang randomly, until another request is made to dbmail, and then it resumes.
This points to an issue with dbmail, rather than with the java client, but it's random as to when/where it hangs.
I'll do some more digging, trying a python client instead.
Have you run into anything like this before?

**Comment by awheeler** [comment]
ok, replicated this in a python client, so definitely in dbmail

**Comment by CozC** [comment]
Salve,

I would check the mysql (or storage queries, not the one reported by  
DBMail logs), to see if there would be an error related to an uncaught sql  
error. I found out that there are times when it just aborts. Also you can  
try run it with valgrind (if you need more info, I'll send gcc parameters  
I usually use).



On Wed, 08 Apr 2020 20:09:42 +0300, Alex Wheeler  
<notifications@github.com> wrote:

>
> ok, replicated this in a python client, so definitely in dbmail
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
@awheeler,  any news related to this issues on your side?

**Comment by CozC** [comment]
No more information and activity closing.
