### ISSUE TITLE
Failure to install on Fedora

### ISSUE THREAD

**Issue by LOTRg** [dbmail/dbmail#38]
Can we have a packaged version, or rather a repo, for fedora please ?
I'm unable to find a usable RPM version on Fedora 31 server.

Thank you

**Comment by CozC** [comment]
Salve,

Unfortunately, we do not provide a rpm version, but is planned to some  
degree (at least for Centos). Given the fact that fedora is compatible to  
some degree with Centos that may work. At this point I cannot give a  
timetable for the packaged version.
If you are in a hurry I can give you some assistance to build it (From the  
complexity stand point is not hard but some devel libraries may need to be  
installed on the target system)

--
Cosmin Cioranu

**Comment by LOTRg** [comment]
@CozC Thank you for your prompt response . I do appreciate your input, I have took a stab at building an RPM myself on Fedora 31 and I am in the process of testing it now, I will update and share instructions for fellow users who may be interested once I verify the file against my current (ArchLinux) instance since it is available natively in Arch.

**Comment by CozC** [comment]
@LOTRg If you do manage to build up some guidelines (or even more, an  
entire procedure), I'll more then happy to integrate it at DBMail level  
(or pull request to be accepted)



On Thu, 23 Apr 2020 00:51:22 +0300, LOTRg <notifications@github.com> wrote:

>
> @CozC Thank you for your prompt response . I do appreciate your input, I  
> have took a stab at building an RPM myself on Fedora 31 and I am in the  
> >process of testing it now, I will update and share instructions for  
> fellow users who may be interested once I verify the file against my  
> current >(ArchLinux) instance since it is available natively in Arch.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by LOTRg** [comment]
@CozC I have built the RPM for DBMail and have tested it and it works. I have also wrote a guide on how to build on Fedora and CentOS. I am not sure how to share the guide and the needed SPEC files for the build, please advice and hopefully we can further test this on CentOS 7, 8 and Fedora versions and may be we can make this available for the masses or at least integrated into the project if an RPM won't be maintained.

**Comment by CozC** [comment]
@LOTRg, good job.
I do think everyone should be recognized oft their own achievements, so  
the best way to share this by initiating a pull request.
You may know the steps, but some other readers may benefit upon reading  
this later on.
So, first fork the dbmail project into your account. Second, but this is  
optionally, create a branch (in your own forked copy of dbmail). Checkout  
on your system/computer/workstation this branch (or dbmail forked  
project). Create a new folder in contrib (eg: ./contrib/build-rpm) and put  
there the spec file and the readme containing the guide. Push the new  
files and issue a pull request towards dbmail.
I will review it and if everything checks out I will approve the  
modifications. Do not forget to put your name there.

Thank you for your effort.

-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Resulted in pull request.
