### ISSUE TITLE
Help Needed - DBMail Administration

### ISSUE THREAD

**Issue by LOTRg** [dbmail/dbmail#43]
Apologies for creating an issue but I couldn't find the forums to post.

Can someone please point me to a DBMail administration tool like dbmailadmin or something else ? Is it Possible to have instructions on how to setup whatever tools you suggest ? or share - How you manage DBMail with Aliases and Virtual Domains  ?

Thanks in Advance

**Comment by CozC** [comment]
On DBMail github, not so much information can be found, but on the old  
docuwiki ( http://dbmail.org/dokuwiki/doku.php ) you may find other useful  
data. However, the official tools to manage DBMail are:
- dbmail-user: manage users, aliases and so on
- dbmail-util: manage messages and cleanups

Some examples.
; create user
# dbmail-users -a [username] -s [alias email] -w [password]

; add alias
#dbmail-users -c [username] -s [alias email]

;list information
# dbmail-users -l [username]

;add to forward
dbmail-users -x [localemail] -t [destination email]

Also, I you wish to create an user via SQL, you can use (this will use  
plaintext store of an email)

set @L_USER='[user]';
set @L_PASSWD='[password]';
set @L_ALIAS='[email]';

insert into dbmail_users set userid=@L_USER, passwd=@L_PASSWD,  
encryption_type='';
insert into dbmail_aliases set alias=@L_ALIAS, deliver_to=(select  
user_idnr from dbmail_users where userid=@L_USER);
insert into dbmail_mailboxes set name='INBOX', owner_idnr=(select  
user_idnr from dbmail_users where userid=@L_USER);
insert into dbmail_mailboxes set name='Sent', owner_idnr=(select user_idnr  
 from dbmail_users where userid=@L_USER);
insert into dbmail_mailboxes set name='Trash', owner_idnr=(select  
user_idnr from dbmail_users where userid=@L_USER);
insert into dbmail_mailboxes set name='Spam', owner_idnr=(select user_idnr  
 from dbmail_users where userid=@L_USER);


Hope it helps.


On Sun, 26 Apr 2020 07:25:16 +0300, LOTRg <notifications@github.com> wrote:

>
> Apologies for creating an issue but I couldn't find the forums to post.
>
> Can someone please point me to a DBMail administration tool like  
> dbmailadmin or something else ? Is it Possible to have instructions on  
> how to >setup whatever tools you suggest ? or share - How you manage  
> DBMail with Aliases and Virtual Domains ?
>
> Thanks in Advance
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
However, the virtual domain, if you are referring to MTA perspective is another matter. It will be linked directly to database backend (postfix wise)

**Comment by LOTRg** [comment]
Thanks for the information @CozC . Closing this as Alternate solution has been provided.
