### ISSUE TITLE
Multiple duplicated messages in mailboxes

### ISSUE THREAD

**Issue by dannysauer** [dbmail/dbmail#45]
This seems like a situation which should not be:

```
MariaDB [dbmail]> SELECT COUNT(*) AS cnt, mailbox_idnr, physmessage_id
    ->   FROM dbmail_messages 
    ->   GROUP BY physmessage_id, mailbox_idnr 
    ->   ORDER BY cnt DESC LIMIT 5;
+-----+--------------+----------------+
| cnt | mailbox_idnr | physmessage_id |
+-----+--------------+----------------+
|  26 |            5 |        2036654 |
|  26 |            5 |        2036655 |
|  26 |            5 |        2036650 |
|  26 |            5 |        2036653 |
|  26 |            5 |        2036652 |
+-----+--------------+----------------+
```

Am I misunderstanding the schema, bad at SQL, or the proud owner of a database where a bunch of messages are duplicated?

If the latter, there might be quite a few duplicates...
```
MariaDB [dbmail]> SELECT COUNT(*) AS dupcnt, mailbox_idnr FROM
    -> ( SELECT COUNT(*) AS cnt, mailbox_idnr, physmessage_id 
    ->   FROM dbmail_messages GROUP BY physmessage_id, mailbox_idnr ORDER BY cnt DESC
    -> ) dups WHERE cnt > 1 GROUP BY mailbox_idnr ORDER BY dupcnt DESC LIMIT 5;
+--------+--------------+
| dupcnt | mailbox_idnr |
+--------+--------------+
|  53606 |            5 |
|    820 |           77 |
|     29 |          129 |
|     21 |          147 |
|      4 |          130 |
+--------+--------------+
```

Should I perhaps remove all but one of those duplicated mailbox entries pointing at the same physmessage, or is this situation actually just fine?

**Comment by CozC** [comment]
Salve,

Usually, in myexperience that happens when postfix (or your mta) sends the  
email more than one time via lmtp (or smtd) daemon,  due to a  
missconfiguration where the mail bouceback and postfix resends it, but he  
cannot so it pushes it into the queue. In the end when the configuration  
gets fixed all emails are sent to dbmail so... duplicates are created.
Also, note, that dbmail has some features to identify the same mail and  
redirects it internally to the same physical email.
All my cases of duplicates goes back to this case if the case of same  
folder.

If you find duplicates across folders that that is related to copy of  
messages (even trash) so in that case should be checked the status field.
Status=2 => deleted.

SELECT COUNT(*) AS dupcnt, mailbox_idnr FROM
( SELECT COUNT(*) AS cnt, mailbox_idnr, physmessage_id
 FROM dbmail_messages WHERE STATUS<2 GROUP BY physmessage_id, mailbox_idnr  
having cnt>1 ORDER BY cnt DESC
) dups WHERE true GROUP BY mailbox_idnr ORDER BY dupcnt

So bottom line check your config, and mostly the lmtpd daemon for  
stability.
You can delete (status=2) the duplicates but be aware of the seq field.  
Run dbmail-util to check everything afterworlds

Hope it helps.


On Fri, 01 May 2020 04:56:30 +0300, Danny Sauer <notifications@github.com>  
wrote:

>
> This seems like a situation which should not be:
> MariaDB [dbmail]> SELECT COUNT(*) AS cnt, mailbox_idnr, physmessage_id
>    ->   FROM dbmail_messages   ->   GROUP BY physmessage_id, mailbox_idnr 
>    ->   ORDER BY cnt DESC LIMIT 5;
> +-----+--------------+----------------+
> | cnt | mailbox_idnr | physmessage_id |
> +-----+--------------+----------------+
> |  26 |            5 |        2036654 |
> |  26 |            5 |        2036655 |
> |  26 |            5 |        2036650 |
> |  26 |            5 |        2036653 |
> |  26 |            5 |        2036652 |
> +-----+--------------+----------------+
>
> Am I misunderstanding the schema, bad at SQL, or the proud owner of a  
> database where a bunch of messages are duplicated?
>
> If the latter, there might be quite a few duplicates...
> MariaDB [dbmail]> SELECT COUNT(*) AS dupcnt, mailbox_idnr FROM
>    -> ( SELECT COUNT(*) AS cnt, mailbox_idnr, physmessage_id   ->   FROM  
> dbmail_messages GROUP BY physmessage_id, mailbox_idnr ORDER BY cnt DESC
>    -> ) dups WHERE cnt > 1 GROUP BY mailbox_idnr ORDER BY dupcnt DESC  
> LIMIT 5;
> +--------+--------------+
> | dupcnt | mailbox_idnr |
> +--------+--------------+
> |  53606 |            5 |
> |    820 |           77 |
> |     29 |          129 |
> |     21 |          147 |
> |      4 |          130 |
> +--------+--------------+
>
> Should I perhaps remove all but one of those duplicated mailbox entries  
> pointing at the same physmessage, or is this situation actually just  
> fine?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by dannysauer** [comment]
I agree with that guess, and have suspected for a while that this might have happened due to having a very unstable mail environment (I was running MySQL and dbmail (and some other stuff)) on a VPS with 512MB total.  So the OOM killer would regularly wipe mysql and/or dbmail processes out, and a cron job running every minute would then restart it all.  It was a horrible mess. :D

I finally got around to moving these components to some much better VMs (specifically with database separated from email), and finally upgraded from 2.2.  Performance is not what I'd expect, though, and I suspect that the duplicates are making simple queries take way longer than they should.

In any event, none of these messages have the delete status set.  I had run dbmail-util to purge those already.

**Comment by dannysauer** [comment]
So, say I have this situation:
```
MariaDB [dbmail]> SELECT mailbox_idnr, physmessage_id, message_idnr, status, seq
 FROM dbmail_messages WHERE physmessage_id = 1963736;
+--------------+----------------+--------------+--------+-----+
| mailbox_idnr | physmessage_id | message_idnr | status | seq |
+--------------+----------------+--------------+--------+-----+
|            1 |        1963736 |      4371457 |      0 |   0 |
|           77 |        1963736 |      4372357 |      0 |   0 |
|           77 |        1963736 |      4372361 |      0 |   0 |
|           77 |        1963736 |      4372392 |      0 |   0 |
+--------------+----------------+--------------+--------+-----+
```

I should be able to delete 4372361 and 4372392, leaving just one message linking to the same pysmessage in mailbox 1 and one in mailbox 77, right?  Should I keep the lowest `message_idnr`, the highest `message_idnr`, or use some other criteria?  Are there other criteria I would need to consider for this deletion?

I was thinking something like this if I was to keep one each of the lowest idnr:
```mysql
DELETE m1
FROM dbmail_messages m1 
INNER JOIN dbmail_messages m2
  ON m1.message_idnr > m2.message_idnr 
  AND m1.physmessage_id = m2.physmessage_id
  AND m1.mailbox_idnr = m2.mailbox_idnr
```

If I do a select (rather than delete) with that and include `WHERE m1.physmessage_id = 1963736`, I get this, which _looks_ right (aside from the duplicate due to the join):
```
+--------------+----------------+--------------+
| mailbox_idnr | physmessage_id | message_idnr |
+--------------+----------------+--------------+
|           77 |        1963736 |      4372361 |
|           77 |        1963736 |      4372392 |
|           77 |        1963736 |      4372392 |
+--------------+----------------+--------------+
```

**Comment by dannysauer** [comment]
I'm also curious if this duplicated message in inbox (though probably, one-at-a-time, like the other cleanup operations) might be something useful to include in `dbmail-util`.

**Comment by CozC** [comment]
Salve,

512M RAM server seems to be a little bit lower and may account for the  
duplications.
Yes, the duplicates do burden the daemon (dbmail-imap) on retrieving the  
messages.
Please note the following: the official version 3.2.3 do take into  
consideration also the status=2 and status=3 on selecting the folder so  
even if you mark those messages as deletable or purgeable it will not make  
much of a difference, you should consider purge them out from db (using  
dbmail-util). The current master branch does have updates in place to  
solve the issue. In terms of stability I do strive to have it in working  
order every time.
Thanks to the efforts of @LOTr we will have soon also a rpm packaged  
version.

Hope it helps.

On Fri, 01 May 2020 19:58:56 +0300, Danny Sauer <notifications@github.com>  
wrote:

>
> I agree with that guess, and have suspected for a while that this might  
> have happened due to having a very unstable mail environment (I was  
> running >MySQL and dbmail (and some other stuff)) on a VPS with 512MB  
> total. So the OOM killer would regularly wipe mysql and/or dbmail  
> processes out, >and a cron job running every minute would then restart  
> it all. It was a horrible mess. :D
>
> I finally got around to moving these components to some much better VMs  
> (specifically with database separated from email), and finally upgraded  
> >from 2.2. Performance is not what I'd expect, though, and I suspect  
> that the duplicates are making simple queries take way longer than they  
> should.
>
> In any event, none of these messages have the delete status set. I had  
> run dbmail-util to purge those already.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Salve,
Given the fact the messages are the same I would keep the first one (you  
would like to keep the order of receiving messages). Keep in mind that  
deleting them from db directly does imply setting the status=2 and then  
use dbmail-util to purge them (which will fix the seq field if necessary)  
This hopefully answer the second question also.



On Fri, 01 May 2020 20:18:37 +0300, Danny Sauer <notifications@github.com>  
wrote:

>
> So, say I have this situation:
> MariaDB [dbmail]> SELECT mailbox_idnr, physmessage_id, message_idnr,  
> status, seq
> FROM dbmail_messages WHERE physmessage_id = 1963736;
> +--------------+----------------+--------------+--------+-----+
> | mailbox_idnr | physmessage_id | message_idnr | status | seq |
> +--------------+----------------+--------------+--------+-----+
> |            1 |        1963736 |      4371457 |      0 |   0 |
> |           77 |        1963736 |      4372357 |      0 |   0 |
> |           77 |        1963736 |      4372361 |      0 |   0 |
> |           77 |        1963736 |      4372392 |      0 |   0 |
> +--------------+----------------+--------------+--------+-----+
>
> I should be able to delete 4372361 and 4372392, leaving just one message  
> linking to the same pysmessage in mailbox 1 and one in >mailbox 77,  
> right? Should I keep the lowest message_idnr, the highest message_idnr,  
> or use some other criteria? Are there >other criteria I would need to  
> consider for this deletion?
>
> I was thinking something like this if I was to keep one each of the  
> lowest idnr:
> DELETE m1
> FROM dbmail_messages m1INNER JOIN dbmail_messages m2
>  ON m1.message_idnr > m2.message_idnr AND m1.physmessage_id =  
> m2.physmessage_id
>  AND m1.mailbox_idnr = m2.mailbox_idnr
>
> If I do a select (rather than delete) with that and include WHERE  
> m1.physmessage_id = 1963736, I get this, which looks right >(aside from  
> the duplicate due to the join):
> +--------------+----------------+--------------+
> | mailbox_idnr | physmessage_id | message_idnr |
> +--------------+----------------+--------------+
> |           77 |        1963736 |      4372361 |
> |           77 |        1963736 |      4372392 |
> |           77 |        1963736 |      4372392 |
> +--------------+----------------+--------------+
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Salve,

Good suggestion, but I would include this feature only for duplicates in  
the same mailbox. Duplicates across folders may be a valid due to  
copy/move messages (e.g. from mailbox to trash situation)
Please create a new issue related to dbmail-util  (I do ask you to do it  
in order to have a correct record) and label it as feature

Thank you.

On Fri, 01 May 2020 20:19:56 +0300, Danny Sauer <notifications@github.com>  
wrote:

>
> I'm also curious if this duplicated message in inbox (though probably,  
> one-at-a-time, like the other cleanup operations) might be something  
> useful to >include in dbmail-util.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by dannysauer** [comment]
I ended up using the inner join, since doing an update or delete with the "where id in (select)" style query complains on MySQL because you're updating the table being used as a source. :/
```mysql
UPDATE dbmail_messages m1 INNER JOIN dbmail_messages m2
  ON m1.message_idnr > m2.message_idnr
  AND m1.physmessage_id = m2.physmessage_id
  AND m1.mailbox_idnr = m2.mailbox_idnr 
SET m1.status = 2;
```
It took about 5 minutes to flag up the ~1.2 million dups (on a 4-CPU / 8GB Digital Ocean droplet). :D

Then running `dbmail-util -dpy` once set the status=2s to status=3s (as expected), and the second run purged them.

Things seems happier now.  Closing ticket.

**Comment by CozC** [comment]
I'm glad,
As a further note:
In the future if you wish to use delete a little bit faster, use a  
temporary table with an index and then a delete
`create temporary table x as select v1, v2 from .... ;
  alter table x add index (v1) ;
  delete from dbmail... where id in select(v1) from x;
`
In this way you can check the results and the possibility of errors (or  
mistakes) drops pretty much.

Hope it helps.


On Mon, 04 May 2020 06:47:22 +0300, Danny Sauer <notifications@github.com>  
wrote:

>
> I ended up using the inner join, since doing an update or delete with  
> the "where id in (select)" style query complains on MySQL because you're  
> >updating the table being used as a source. :/
> UPDATE dbmail_messages m1 INNER JOIN dbmail_messages m2
>  ON m1.message_idnr > m2.message_idnr
>  AND m1.physmessage_id = m2.physmessage_id
>  AND m1.mailbox_idnr = m2.mailbox_idnrSET m1.status = 2;
>
> It took about 5 minutes to flag up the ~1.2 million dups (on a 4-CPU /  
> 8GB Digital Ocean droplet). :D
>
> Then running dbmail-util -dpy once set the status=2s to status=3s (as  
> expected), and the second run purged them.
>
> Things seems happier now. Closing ticket.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu
