### ISSUE TITLE
Changelog 

### ISSUE THREAD

**Issue by langemeijer** [dbmail/dbmail#7]
Since commit 7e0bf6d the changelog is not in the projects repository anymore.

Can we restore it back into the project? The ChangeLog file only contains a link to 
http://git.dbmail.eu/paul/dbmail/log/ which doesn't work.

What is this link http://git.dbmail.eu/?p=paul/dbmail;a=log

I'm happy to do the administrative work of re-creating the changelog for the changes in the last few years if that is the problem. 

It would be very helpfull if we can have a document with changes between releases.

**Comment by CozC** [comment]
I can help you with my own additions (and some of the pull requests I have merged). Another idea is to take a look over the original repository and browse through comments, we may find some useful info.

**Comment by CozC** [comment]
the change log has been added following changes since 2019. Other might be missed, but additions are welcome.
