### ISSUE TITLE
function group_concat(character varying) does not exist in PostgreSQL

### ISSUE THREAD

**Issue by alan-hicks** [dbmail/dbmail#75]
Version 3.2.4 has hit FreeBSD ports and 
Error:[MailboxState] MailboxState_new(+331): SQLException: ERROR:  function group_concat(character varying) does not exist

This appears to be an issue for PostgreSQL users as group_concat is MySQL

There is a discussion on stackoverflow that might help
https://stackoverflow.com/questions/2560946/postgresql-group-concat-equivalent

**Comment by CozC** [comment]
Given the changes this can be changed in non group_concat query.
I'll make the changes as soon as I find some little time.
Thank your for the effort in offering potential solutions.
-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Pushed changes to solve the issue. You are welcome to review them. ------ Original message------From: Cosmin CIORANUDate: Fri, Jun 26, 2020 20:46To: dbmail/dbmail;Alan Hicks;dbmail/dbmail;Cc: Subscribed;cosmin.cioranu@gmail.com;Subject:Re: [dbmail/dbmail] function group_concat(character varying) does not exist in PostgreSQL (#75)Given the changes this can be changed in non group_concat query. I'll make the changes as soon as I find some little time. Thank your for the effort in offering potential solutions. 
-- Cosmin CioranuOn Fri, 26 Jun 2020 15:10:23 +0300, Alan Hicks > wrote:
Version 3.2.4 has hit FreeBSD ports and
Error:[MailboxState] MailboxState_new(+331): SQLException: ERROR:  function group_concat(character varying) does not exist
This appears to be an issue for PostgreSQL users as group_concat is MySQL
There is a discussion on stackoverflow that might help
https://stackoverflow.com/questions/2560946/postgresql-group-concat-equivalent
