### ISSUE TITLE
systemd units changed to type simple

### ISSUE THREAD

**Issue by cjmayo** [dbmail/dbmail#8]
@langemeijer what prompted the change of Type for the systemd units from notify to simple in https://github.com/dbmail/dbmail/commit/4de4bc5d9c10be5acdf1c8bde03b63e82f33e611 ?
Is there something that needs fixing?

**Comment by langemeijer** [comment]
This could well be that it's just what I had, before you commited and pushed revision c6773f6b5ff6d87513c3759565df1700128c7e42

We came from 'forking' and that caused my processes to disappear on crashes. I used simple and the commandline -D switch to stop the forking.

I agree that 'notify' should be te desired method.

**Comment by cjmayo** [comment]
Good to know there weren't any issues.
I've created #11 to put them back.
