### ISSUE TITLE
implement/update debian package build

### ISSUE THREAD

**Issue by ezplanet** [dbmail/dbmail#91]
Is there a way to build a debian package with the new 3.2.4 release? I tried to follow the process that I used for dbmail 3.2.3 but this is what I get:

$ dpkg-buildpackage -uc -us -t
dpkg-buildpackage: info: source package dbmail
dpkg-buildpackage: info: source version 3.2.3-3
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Casper Langemeijer <casper@procurios.nl>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 fakeroot debian/rules clean
test -x debian/rules
rm -f debian/stamp-makefile-build debian/stamp-makefile-install
/usr/bin/make -C . -k distclean
make[1]: Entering directory '/tank/downloads/dbmail/dbmail-3.2.4'
make[1]: *** No rule to make target 'distclean'.
make[1]: Leaving directory '/tank/downloads/dbmail/dbmail-3.2.4'
make: [/usr/share/cdbs/1/class/makefile.mk:91: makefile-clean] Error 2 (ignored)
rm -f debian/stamp-autotools
rmdir --ignore-fail-on-non-empty .
rmdir: failed to remove '.': Invalid argument
make: [/usr/share/cdbs/1/class/autotools.mk:64: makefile-clean] Error 1 (ignored)
set -e;    
dh_clean 
rm -f debian/stamp-autotools-files
 dpkg-source -b .
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../dbmail_3.2.3.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 255

the line "dpkg-buildpackage: info: source version 3.2.3-3" might mean that the debian build files have not been updated to the new version.

but I guess that is not the only reason it fails.

I am using a Ubuntu Mate 20.04 LTS workstation.

Thanks, Mauro

**Comment by CozC** [comment]
Salve,

The new DBMail release did not change anything in terms of dependencies,  
it should have worked, but indeed the change log information was missed.
I will take a look, although I have never worked with debian packaging  
system, it may take a while. So, if you have more info It is welcomed

Have a nice day.

-- 
Cosmin Cioranu

**Comment by LicoMonch** [comment]
> dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../dbmail_3.2.3.orig.tar.{bz2,gz,lzma,xz}

Fix that and you should be fine.

**Comment by CozC** [comment]
Thank you. I'll give it a try

**Comment by ezplanet** [comment]
I have now managed to create a .deb package as follows:

- I added the missing changelog entries to debian/changelog (this allows the correct tar/deb version to be created)
- I removed debian/source/format (this solves can't build with source format...)
- I installed all the missing dependencies that the build was complaining about

**Comment by CozC** [comment]
Thanks,

That was helpful. Can you share them or create a pull request?

Thank you.

On Fri, 07 Aug 2020 11:33:51 +0300, Mauro Mozzarelli  
<notifications@github.com> wrote:

>
> I have now managed to create a .deb package as follows:
> I added the missing changelog entries to debian/changelog (this allows  
> the correct tar/deb version to be created)
> I removed debian/source/format (this solves can't build with source  
> format...)
> I installed all the missing dependencies that the build was complaining  
> about
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by ezplanet** [comment]
OK, I will

**Comment by ezplanet** [comment]
Is master the most up to date with release 3.2.5? If not what is the latest branch?

**Comment by CozC** [comment]
Master is the most up to date.

On Fri, 07 Aug 2020 12:03:22 +0300, Mauro Mozzarelli  
<notifications@github.com> wrote:

>
> Is master the most up to date with release 3.2.5? If not what is the  
> latest branch?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by anton-com** [comment]
when running deb package built from Master the /@runstatedir@ is created on filesystem root (as it is not correctly defined)
systemd services is bit outdated as deb using  mysql.service and not mysqld.service, so for better compatibility mysql.service should be added also to dbmail/systemd scripts

**Comment by cncioranu** [comment]
@anton-com given that you seem knowledgeable about the issue may I ask you to change/modify the configuration in order to reflect what you have suggested and then PR your changes?

It will be an enormous benefit to all to fix issues that may arise with this project.

**Comment by ezplanet** [comment]
PR with updated debian build configuration is merged into master
