### ISSUE TITLE
dbmail/lmtpd[1466]: EMERGENCY:[iconv] dbmail_iconv_once(+65): iconv failure

### ISSUE THREAD

**Issue by anton-com** [dbmail/dbmail#92]
Trying to get dbmail running on new Ubuntu 20.04 server, getting this message in terminal every time new message arrives, dbmail/lmtpd[1466]: EMERGENCY:[iconv] dbmail_iconv_once(+65): iconv failure
Also messaged didn`t get stored to db

**Comment by CozC** [comment]
Salve,

Please check the database encoding and the encoding flag in dbmail.conf.  
It should be the same
It also might be something wrong with iconv lib.

//----
GETCONFIGVALUE("ENCODING", "DBMAIL", ic->db_charset);
...
...
TRACE(TRACE_DEBUG,"Initialize DB encoding surface [UTF-8..%s]",  
ic->db_charset);
ic->to_db = g_mime_iconv_open(ic->db_charset,"UTF-8");
if (ic->to_db == (iconv_t)-1)
TRACE(TRACE_EMERG, "iconv failure");
//----

In order to properly debug the issue, set the
file_logging_levels = 511
syslog_logging_levels = 511

Run it until the issue happens and check the logs (careful not send those  
logs away, it might contain sensitive info)

-- 
Cosmin Cioranu

**Comment by anton-com** [comment]
I am using mysql  Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64 ((Ubuntu)) as database
[DBMAIL]
dburi = mysql://localhost:3306/dbmail_db?charset=utf8mb4&user=dbmail_user&password=dbmail_pass
authdriver           = sql
table_prefix         = dbmail_ #this is not respected by some db mail components so DO NOT CHANGE
encoding             = utf8mb4 #real utf8 for mysql (may be this have to do with the problem)
default_msg_encoding = utf8

Traces with useful info
Aug 07 03:00:01 dev-mail dbmail-util[2365]: [0x56331ec56800] Debug:[iconv] dbmail_iconv_once(+53): key "ENCODING" section "DBMAIL" var ic->db_charset value [utf8mb4]
Aug 07 03:00:01 dev-mail dbmail-util[2365]: [0x56331ec56800] Debug:[iconv] dbmail_iconv_once(+54): key "DEFAULT_MSG_ENCODING" section "DBMAIL" var ic->msg_charset value [utf8]
Aug 07 03:00:01 dev-mail dbmail-util[2365]: [0x56331ec56800] Debug:[iconv] dbmail_iconv_once(+62): Initialize DB encoding surface [UTF-8..utf8mb4]
Aug 07 03:00:01 dev-mail dbmail-util[2365]: [0x56331ec56800] EMERGENCY:[iconv] dbmail_iconv_once(+65): iconv failure

Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Debug:[config] config_get_timeout(+483): timeout [300] seconds
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Debug:[config] config_get_timeout(+493): login_timeout [60] seconds
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Notice:[server] server_run(+770): starting main service loop for [LMTP]
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Debug:[db] db_connect(+213): dburi: mysql://dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-lmtpd
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Database:[db] db_connect(+261): db at dburi: [mysql://dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-lmtpd]
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Info:[db] db_connect(+271): database connection pool created with maximum connections of [10]
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Database:[db] db_connect(+275): run a database connection reaper thread every [60] seconds
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Debug:[config] config_get_timeout(+483): timeout [4000] seconds
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Debug:[config] config_get_timeout(+493): login_timeout [60] seconds
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Notice:[server] server_run(+770): starting main service loop for [IMAP]
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Debug:[db] db_connect(+213): dburi: mysql://dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-imapd
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Database:[db] db_connect(+261): db at dburi: [mysql://dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-imapd]
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Info:[db] db_connect(+271): database connection pool created with maximum connections of [10]
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Database:[db] db_connect(+275): run a database connection reaper thread every [60] seconds
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Alert:[libzdb] TabortHandler(+45): SQLException: Failed to start connection pool -- Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
 raised in ConnectionPool_start at src/db/ConnectionPool.c:295
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Alert:[libzdb] TabortHandler(+45): SQLException: Failed to start connection pool -- Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
 raised in ConnectionPool_start at src/db/ConnectionPool.c:295
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Database:[db] db_connect(+279): database connection pool started with [5] connections, max [10]
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Database:[db] db_connect(+279): database connection pool started with [5] connections, max [10]
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Alert:[db] db_connect(+283): error getting a database connection from the pool
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Alert:[db] db_connect(+283): error getting a database connection from the pool
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Error:[server] server_run(+774): could not connect to database
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Error:[server] server_run(+774): could not connect to database
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Info:[server] server_mainloop(+993): leaving main loop
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Info:[server] server_mainloop(+993): leaving main loop
Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Info:[lmtpd] main(+50): exit
Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Info:[imapd] main(+55): return [0]
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Debug:[sort] sort_load_driver(+70): looking for sort_sieve as /usr/src/dbmail/src/modules/.libs/libsort_sieve.so
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Debug:[sort] sort_listextensions(+820): Sieve vacation enabled.
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Error:[sort] sort_listextensions(+824): Sieve notify is not supported in this release.
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Debug:[sort] sort_listextensions(+828): Sieve debugging enabled.
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Debug:[config] config_get_timeout(+483): timeout [300] seconds
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Debug:[config] config_get_timeout(+493): login_timeout [60] seconds
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Notice:[server] server_run(+770): starting main service loop for [SIEVE]
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Debug:[db] db_connect(+213): dburi: mysql://dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-timsieved
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Database:[db] db_connect(+261): db at dburi: [mysql://dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-timsieved]
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Info:[db] db_connect(+271): database connection pool created with maximum connections of [10]
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Database:[db] db_connect(+275): run a database connection reaper thread every [60] seconds
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Alert:[libzdb] TabortHandler(+45): SQLException: Failed to start connection pool -- Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
 raised in ConnectionPool_start at src/db/ConnectionPool.c:295
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Database:[db] db_connect(+279): database connection pool started with [5] connections, max [10]
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Alert:[db] db_connect(+283): error getting a database connection from the pool
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Error:[server] server_run(+774): could not connect to database
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Info:[server] server_mainloop(+993): leaving main loop
Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200] Info:[timsieved] main(+62): exit

**Comment by CozC** [comment]
Salve,

Thank you for the log.
I'll try to see if the utf8mb4 is the issue with gmime 2.6.
I suspect issues might be coming from here.

Have a nice day.

On Fri, 07 Aug 2020 12:03:52 +0300, anton-com <notifications@github.com>  
wrote:

>
> I am using mysql Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64  
> ((Ubuntu)) as database
> [DBMAIL]
> dburi =  
> mysql://localhost:3306/dbmail_db?charset=utf8mb4&user=dbmail_user&password=dbmail_pass
> authdriver = sql
> table_prefix = dbmail_ #this is not respected by some db mail components  
> so DO NOT CHANGE
> encoding = utf8mb4 #real utf8 for mysql (may be this have to do with the  
> problem)
> default_msg_encoding = utf8
>
> Traces with useful info
> Aug 07 03:00:01 dev-mail dbmail-util[2365]: [0x56331ec56800]  
> Debug:[iconv] dbmail_iconv_once(+53): key "ENCODING" section "DBMAIL"  
> >var ic->db_charset value [utf8mb4]
> Aug 07 03:00:01 dev-mail dbmail-util[2365]: [0x56331ec56800]  
> Debug:[iconv] dbmail_iconv_once(+54): key "DEFAULT_MSG_ENCODING"  
> >section "DBMAIL" var ic->msg_charset value [utf8]
> Aug 07 03:00:01 dev-mail dbmail-util[2365]: [0x56331ec56800]  
> Debug:[iconv] dbmail_iconv_once(+62): Initialize DB encoding surface  
> >[UTF-8..utf8mb4]
> Aug 07 03:00:01 dev-mail dbmail-util[2365]: [0x56331ec56800]  
> EMERGENCY:[iconv] dbmail_iconv_once(+65): iconv failure
>
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Debug:[config] config_get_timeout(+483): timeout [300] seconds
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Debug:[config] config_get_timeout(+493): login_timeout [60] seconds
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Notice:[server] server_run(+770): starting main service loop for [LMTP]
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Debug:[db]  
> db_connect(+213): dburi:  
> mysql://>dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-lmtpd
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Database:[db] db_connect(+261): db at dburi:  
> [mysql://>dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-lmtpd]
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Info:[db]  
> db_connect(+271): database connection pool created with >maximum  
> connections of [10]
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Database:[db] db_connect(+275): run a database connection reaper thread  
> >every [60] seconds
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Debug:[config] config_get_timeout(+483): timeout [4000] seconds
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Debug:[config] config_get_timeout(+493): login_timeout [60] seconds
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Notice:[server] server_run(+770): starting main service loop for [IMAP]
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Debug:[db]  
> db_connect(+213): dburi:  
> mysql://>dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-imapd
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Database:[db] db_connect(+261): db at dburi:  
> [mysql://>dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-imapd]
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Info:[db]  
> db_connect(+271): database connection pool created with >maximum  
> connections of [10]
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Database:[db] db_connect(+275): run a database connection reaper thread  
> >every [60] seconds
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Alert:[libzdb] TabortHandler(+45): SQLException: Failed to start  
> connection >pool -- Can't connect to local MySQL server through socket  
> '/var/run/mysqld/mysqld.sock' (2)
> raised in ConnectionPool_start at src/db/ConnectionPool.c:295
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Alert:[libzdb] TabortHandler(+45): SQLException: Failed to start  
> connection >pool -- Can't connect to local MySQL server through socket  
> '/var/run/mysqld/mysqld.sock' (2)
> raised in ConnectionPool_start at src/db/ConnectionPool.c:295
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Database:[db] db_connect(+279): database connection pool started with  
> [5] >connections, max [10]
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Database:[db] db_connect(+279): database connection pool started with  
> [5] >connections, max [10]
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200] Alert:[db]  
> db_connect(+283): error getting a database connection from the >pool
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00] Alert:[db]  
> db_connect(+283): error getting a database connection from the >pool
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Error:[server] server_run(+774): could not connect to database
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Error:[server] server_run(+774): could not connect to database
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Info:[server] server_mainloop(+993): leaving main loop
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Info:[server] server_mainloop(+993): leaving main loop
> Aug 06 15:43:41 dev-mail dbmail-lmtpd[871]: [0x5567995af200]  
> Info:[lmtpd] main(+50): exit
> Aug 06 15:43:41 dev-mail dbmail-imapd[876]: [0x7fbedca2ae00]  
> Info:[imapd] main(+55): return [0]
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Debug:[sort] sort_load_driver(+70): looking for sort_sieve as  
> /usr/src/>dbmail/src/modules/.libs/libsort_sieve.so
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Debug:[sort] sort_listextensions(+820): Sieve vacation enabled.
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Error:[sort] sort_listextensions(+824): Sieve notify is not supported in  
> this >release.
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Debug:[sort] sort_listextensions(+828): Sieve debugging enabled.
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Debug:[config] config_get_timeout(+483): timeout [300] seconds
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Debug:[config] config_get_timeout(+493): login_timeout [60] seconds
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Notice:[server] server_run(+770): starting main service loop for [SIEVE]
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Debug:[db] db_connect(+213): dburi:  
> mysql://>dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-timsieved
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Database:[db] db_connect(+261): db at dburi:  
> [mysql://>dbmail:dbmail@localhost:3306/dbmail?application-name=dbmail-timsieved]
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Info:[db] db_connect(+271): database connection pool created with  
> >maximum connections of [10]
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Database:[db] db_connect(+275): run a database connection reaper >thread  
> every [60] seconds
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Alert:[libzdb] TabortHandler(+45): SQLException: Failed to start  
> >connection pool -- Can't connect to local MySQL server through socket  
> '/var/run/mysqld/mysqld.sock' (2)
> raised in ConnectionPool_start at src/db/ConnectionPool.c:295
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Database:[db] db_connect(+279): database connection pool started with  
> >[5] connections, max [10]
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Alert:[db] db_connect(+283): error getting a database connection from  
> >the pool
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Error:[server] server_run(+774): could not connect to database
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Info:[server] server_mainloop(+993): leaving main loop
> Aug 06 15:43:41 dev-mail dbmail-timsieved[870]: [0x5639686b8200]  
> Info:[timsieved] main(+62): exit
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by anton-com** [comment]
After few tests i can confirm that issue is gone when using encoding = utf8. I think gmime is not aware of ut8mb4 as it`s MySQL encoding. So i assume that this config parameter has nothing to do with database encoding and used for the iconv.

**Comment by CozC** [comment]
Looking a little closer to the source code, that specific piece of code is  
building a map in order to store and retrieve data from database.
In other words, dbmail is using internally utf-8, but if your db is  
configured differently it will create a map to translate db-enc->utf-8  
(retrieve) and utf-8-> db-enc(store). As far as I figure, there is no  
mention of utf8mb4 at least in gmime 2.6, maybe in gmime 3.x.
There are plans to include gmime 3.0 but the work was abandoned (there is  
a PR for that)
For now it will remain an open issue, but confirming it by you is by far  
an important step.
-- 
Cosmin Cioranu

**Comment by anton-com** [comment]
I think issue can be closed, as ut8mb4 is MySQL internal encoding, will not be introduced in gmime as there is no need for it. MySQL utf8 is not real utf8 as it uses only 3 bytes instead of 4 for data storage, so later MySQL has introduced the ut8mb4 that is real utf8 with 4bytes. And for all other applications that is same utf8. My misunderstanding was that this config parameter has something to do with db encoding.

**Comment by CozC** [comment]
Thank your for your effort.
We have fixed some issues and also some clarification into the matter was  
given.
If you have other needs that dbmail should implement please ask.

Have a nice day.
-- 
Cosmin Cioranu
