### ISSUE TITLE
dbmail can`t execute upgrade step ALTER TABLE `dbmail_sievescripts`

### ISSUE THREAD

**Issue by anton-com** [dbmail/dbmail#93]
Can`t execute schema upgrade on MySQL 8
BEGIN;
ALTER TABLE `dbmail_sievescripts` CHANGE COLUMN `owner_idnr` `owner_idnr` BIGINT(20) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `dbmail_sievescripts` ADD COLUMN `id` BIGINT(20) UNSIGNED NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);

INSERT INTO dbmail_upgrade_steps (from_version, to_version, applied) values (32001, 32005, now());
COMMIT;

Reson
ALTER TABLE `dbmail_sievescripts` ADD COLUMN `id` BIGINT(20) UNSIGNED NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`)
> 1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
> Time: 0,004s

Traces
]
Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Database:[db] log_query_time(+375): last query took [0] seconds
Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Database:[db] db_con_close(+359): [0x561d72b07390] connection to pool
Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Database:[db] db_con_get(+331): [0x561d72b129a0] connection from pool
Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Database:[db] db_stmt_prepare(+494): [0x561d72b129a0] [SELECT 1=1 FROM dbmail_upgrade_steps WHERE from_version = ? AND to_version = ?]
Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Database:[db] db_stmt_set_int(+508): [0x561d72b240d0] 1:[32001]
Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Database:[db] db_stmt_set_int(+508): [0x561d72b240d0] 2:[32005]
Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Database:[db] db_con_clear(+366): [0x561d72b129a0] connection cleared
Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Info:[db] check_upgrade_step(+1010): Running upgrade step 32001 -> 32005
Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Database:[db] db_exec(+398): [0x561d72b129a0] [BEGIN;
ALTER TABLE `dbmail_sievescripts` CHANGE COLUMN `owner_idnr` `owner_idnr` BIGINT(20) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `dbmail_sievescripts` ADD COLUMN `id` BIGINT(20) UNSIGNED NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);
	
INSERT INTO dbmail_upgrade_steps (from_version, to_version, applied) values (32001, 32005, now());
COMMIT;
]

**Comment by CozC** [comment]
SAlve,

That field is not that important, it is needed to work better with galera  
cluster which does require that all tables sould have a primary key.

On mysql 5 series it is working ok, however it should be tested with "NOT  
NULL" instead of "NULL".
If it does work we will update that upgrade script. Can you confirm?

See bellow.
ALTER TABLE dbmail_sievescripts ADD COLUMN id BIGINT(20) UNSIGNED NOT NULL  
AUTO_INCREMENT FIRST, ADD PRIMARY KEY (id);

Have a nice day.

On Fri, 07 Aug 2020 12:21:50 +0300, anton-com <notifications@github.com>  
wrote:

>
> Cant execute schema upgrade on MySQL 8 BEGIN; ALTER TABLE  
> dbmail_sievescriptsCHANGE COLUMNowner_idnr >owner_idnrBIGINT(20)  
> UNSIGNED NULL DEFAULT NULL; ALTER TABLEdbmail_sievescriptsADD COLUMNid  
> BIGINT(20) >UNSIGNED NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (id`);
>
> INSERT INTO dbmail_upgrade_steps (from_version, to_version, applied)  
> values (32001, 32005, now());
> COMMIT;
>
> Reson
> ALTER TABLE dbmail_sievescripts ADD COLUMN id BIGINT(20) UNSIGNED NULL  
> AUTO_INCREMENT FIRST, ADD PRIMARY KEY (id)
>>
>> 1171 - All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in  
>> a key, use UNIQUE instead
>> Time: 0,004s
>
> Traces
> ]
> Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200]  
> Database:[db] log_query_time(+375): last query took [0] seconds
> Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200]  
> Database:[db] db_con_close(+359): [0x561d72b07390] connection to pool
> Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200]  
> Database:[db] db_con_get(+331): [0x561d72b129a0] connection from pool
> Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200]  
> Database:[db] db_stmt_prepare(+494): [0x561d72b129a0] [SELECT 1=1 >FROM  
> dbmail_upgrade_steps WHERE from_version = ? AND to_version = ?]
> Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200]  
> Database:[db] db_stmt_set_int(+508): [0x561d72b240d0] 1:[32001]
> Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200]  
> Database:[db] db_stmt_set_int(+508): [0x561d72b240d0] 2:[32005]
> Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200]  
> Database:[db] db_con_clear(+366): [0x561d72b129a0] connection cleared
> Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200] Info:[db]  
> check_upgrade_step(+1010): Running upgrade step 32001 -> >32005
> Aug 07 08:43:46 dev-mail dbmail-lmtpd[2916]: [0x561d72ac0200]  
> Database:[db] db_exec(+398): [0x561d72b129a0] [BEGIN;
> ALTER TABLE dbmail_sievescripts CHANGE COLUMN owner_idnr owner_idnr  
> BIGINT(20) UNSIGNED NULL DEFAULT NULL;
> ALTER TABLE dbmail_sievescripts ADD COLUMN id BIGINT(20) UNSIGNED NULL  
> AUTO_INCREMENT FIRST, ADD PRIMARY KEY (id);
>
> INSERT INTO dbmail_upgrade_steps (from_version, to_version, applied)  
> values (32001, 32005, now());
> COMMIT;
> ]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by anton-com** [comment]
Confirmed, working with NOT NULL
Thanks!

**Comment by anton-com** [comment]
The issue is about why server trying to always updated the schema while running, as it was already updated manually.
with the records created in upgrade steps table

**Comment by CozC** [comment]
Pushed a pull request for this issue.


On Fri, 07 Aug 2020 12:37:10 +0300, anton-com <notifications@github.com>  
wrote:

>
> Confirmed, working with NOT NULL
> Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
Please add it as an issue in order to be tracked properly.
This needs a little investigating.

On Fri, 07 Aug 2020 12:38:56 +0300, anton-com <notifications@github.com>  
wrote:

>
> The issue is about why server trying to always updated the schema while  
> running, as it was already updated manually.
> with the records created in upgrade steps table
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by cncioranu** [comment]
Closing, end up with a fix.
