### ISSUE TITLE
Question: Up-to-date database schema

### ISSUE THREAD

**Issue by armatusmiles** [dbmail/dbmail#96]
Where I can find up-to-date database schema for 3.1-3.2 release?
I have found only for 2.0 version https://www.dbmail.org/dokuwiki/doku.php/2.0

**Comment by CozC** [comment]
Salve,

If you had installed the 3.2.x in the past and has worked, any new version  
should install it's upgrades automatically.

If not, that would be a little bit of work, but you can start with  
sql/[type of db]/createTables.sql which seems to be part of the 3.2.x  
version
After installation (the latest version) and running for the first time,  
sql upgrades should executed also (see sql/upgrades)

Have a nice day
-- 
Cosmin Cioranu

**Comment by armatusmiles** [comment]
Sorry for being vague.
But I was interesting in db schema view with description like here: https://www.dbmail.org/dokuwiki/doku.php/2.0
but for 3.1.7 version. 
Because I can't find documentation for new tables ( dbmail_envelope for example )

**Comment by CozC** [comment]
Salve,

Those information found at the specified link is outdated and not  
maintained (actually it is linked to the original developer). Saddly, as  
far as a I know, nobody can update that information.
The development is continued only on gihub, and there the version is 3.2.5

The only thing I can offer you is as I did last time.
The files found on github do contain the updated structure of the dbmail  
schema (mysql, postgresql and sqlite).
The files are found in the ./sql folder and you should star with  
createTable.sql and work your way up until your requested version by using  
either the files found in that folder or the upgrades (the upgrades are  
run by the deamon when it starts)
As far as I knwow 3.1.7 had some issues, some related to segmentation  
fault and some other related to performance.

Hope it helps.
-- 
Cosmin Cioranu

**Comment by armatusmiles** [comment]
Thank you for your help.
Have a nice day!
