### ISSUE TITLE
upgrades/32005.psql syntax error

### ISSUE THREAD

**Issue by tnn2** [dbmail/dbmail#97]
```
dbmail=# \i 32005.psql
BEGIN
psql:32005.psql:3: ERROR:  syntax error at or near "`"
LINE 1: ALTER TABLE `dbmail_sievescripts` CHANGE COLUMN `owner_idnr`...
                    ^
psql:32005.psql:4: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
```

The syntax should be something like
```
ALTER TABLE dbmail_sievescripts ALTER COLUMN owner_idnr DROP NOT NULL;
ALTER TABLE dbmail_sievescripts ALTER COLUMN owner_idnr DEFAULT NULL;
```

Furthermore the declaration of `owner_idnr` looks inconsistent in the upgrade script compared to `create_tables.pgsql` where the column is still set to `NOT NULL`.

**Comment by CozC** [comment]
Salve,

I believe those updates (from the sql) can be removed, there is no sense  
in changing it (pgsql version). I believe it was change that happened in  
mysql and ported to pgsql but those 2 tables were different to begin with.

Thank you.

On Sat, 15 Aug 2020 13:30:57 +0300, Tobias Nygren  
<notifications@github.com> wrote:

> dbmail=# \i 32005.psql
> BEGIN
> psql:32005.psql:3: ERROR:  syntax error at or near "`"
> LINE 1: ALTER TABLE `dbmail_sievescripts` CHANGE COLUMN `owner_idnr`...
>                    ^
> psql:32005.psql:4: ERROR:  current transaction is aborted, commands  
> ignored until end of transaction block
> ROLLBACK
>
> The syntax should be something like
> ALTER TABLE dbmail_sievescripts ALTER COLUMN owner_idnr DROP NOT NULL;
> ALTER TABLE dbmail_sievescripts ALTER COLUMN owner_idnr DEFAULT NULL;
>
> Furthermore the declaration of owner_idnr looks inconsistent in the  
> upgrade script compared to create_tables.pgsql where the column is still  
> set >to NOT NULL.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Cosmin Cioranu

**Comment by CozC** [comment]
see #98
