### ISSUE TITLE
Install for mysql failing (datetime default invalid)

### ISSUE THREAD

**Issue by awakenedtechnologies** [dbmail/dbmail#99]
I am installing dbmail for the first time (git commit afc107aeddde259dd4a41040bfa69c41ce20ada1 on Ubuntu LTS 20.04 LTS)
The included sql/mysql/create_tables.mysql file is setting an invalid datetime default ("0000-00-00 00:00:00") for mysql.
I am using:
Package: mysql-server
Version: 8.0.21-0ubuntu0.20.04.4

I applied these changes for my install, but wanted to call this out:
```diff --git a/sql/mysql/create_tables.mysql b/sql/mysql/create_tables.mysql
index 07ec3449..5840a59a 100644
--- a/sql/mysql/create_tables.mysql
+++ b/sql/mysql/create_tables.mysql
@@ -277,7 +277,7 @@ CREATE TABLE `dbmail_partlists` (
 DROP TABLE IF EXISTS `dbmail_pbsp`;
 CREATE TABLE `dbmail_pbsp` (
   `idnr` bigint(20) UNSIGNED NOT NULL auto_increment,
-  `since` datetime NOT NULL default '0000-00-00 00:00:00',
+  `since` datetime NOT NULL default '1000-01-01 00:00:00',
   `ipnumber` varchar(40) NOT NULL,
   PRIMARY KEY  (`idnr`),
   UNIQUE KEY `ipnumber_index` (`ipnumber`),
@@ -293,7 +293,7 @@ CREATE TABLE `dbmail_physmessage` (
   `id` bigint(20) UNSIGNED NOT NULL auto_increment,
   `messagesize` bigint(20) UNSIGNED NOT NULL default '0',
   `rfcsize` bigint(20) UNSIGNED NOT NULL default '0',
-  `internal_date` datetime NOT NULL default '0000-00-00 00:00:00',
+  `internal_date` datetime NOT NULL default '1000-01-01 00:00:00',
   PRIMARY KEY  (`id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

@@ -320,7 +320,7 @@ CREATE TABLE `dbmail_replycache` (
   `to_addr` varchar(255) NOT NULL default '',
   `from_addr` varchar(255) NOT NULL default '',
   `handle` varchar(255) NOT NULL default '',
-  `lastseen` datetime NOT NULL default '0000-00-00 00:00:00',
+  `lastseen` datetime NOT NULL default '1000-01-01 00:00:00',
   UNIQUE KEY `replycache_1` (`to_addr`,`from_addr`,`handle`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Thanks

**Comment by CozC** [comment]
Salve,

Such default value is present in some other tables too, so those should be  
changed also.
For future reference, older versions of MySQL did not enforce by default  
STRICT_TRANS_TABLES but mysql 8.x does.

Thank you for your input, I'll make a note and change them.

If you have other updates, if you feel like adding them, please do not  
hesitate to write or make a pull request.

Have a nice day,
-- 
Cosmin Cioranu

**Comment by awakenedtechnologies** [comment]
Thanks, I just sent a pull request over for this file and the others under /sql/mysql/ with the same default value.
